### ISSUE TITLE
[Question] How can I create Definitions pack?

### ISSUE THREAD

**Issue by igorissen** [mrkite/minutor#102]
Hi,

Is it possible to create a definition pack for the new version of minecraft ? (1.11)

**Comment by upwhere** [comment]
Ismael Gorissen writes:
> Is it possible to create a definition pack for the new
> version of minecraft ? (1.11)

Yes, there's a [readme]
(https://github.com/mrkite/minutor/tree/master/definitions)
and it should be straightforward if you can read JSON.
However, the ones in the github repository are already for 1.11
so unless they're not to your liking there's nothing you need
to do.

Try to update or import them manually.

**Comment by igorissen** [comment]
@upwhere Thanks. 
Maybe there is an issue because I'm using the latest version on Windows (v2.1.0) and I see this info about definitions :

- Vanilla / 1.9.15w34a / block
- Vanilla / 1.9.15w31 / entity
- Vanilla / 1.6.2 / dimension
- Vanilla / 1.9.15w37a / biome

**Comment by upwhere** [comment]
Ismael Gorissen writes:
> Maybe there is an issue because I'm using the latest version
> on Windows (v2.1.0) and I see this info about definitions :
> 
> - Vanilla / 1.9.15w34a / block
> - Vanilla / 1.9.15w31 / entity
> - Vanilla / 1.6.2 / dimension
> - Vanilla / 1.9.15w37a / biome

Yes, you're right. The release on the website comes with
definitions for 1.9.
Are you able to update them in the definition manager? It should
be as simple as clicking a button. There's also an option to
automatically check for updates in the settings.

If that doesn't work then it would be nice to have an issue
filed for that.

**Comment by igorissen** [comment]
@upwhere Yes, I have cloned your repository in order to use the latest definitions. Next time I'll give a try with the `Check for updates` option.

Thanks.
