### ISSUE TITLE
Crashing at start

### ISSUE THREAD

**Issue by BrunoRMolina** [mrkite/minutor#107]
When i run minutor from terminal i receive that error message

minutor: blockidentifier.cpp:235: void BlockIdentifier::parseDefinition(JSONObject*, BlockInfo*, int): Assertion `blockcolor.isValid()' failed.

Compiled in a linux_x64
QT v5.7.1
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -fpermissive $(DEFINES)

**Comment by EtlamGit** [comment]
It seems from the error message that something fails during one of the "color" parsing in vanilla_ids.json The assertion is intentionally placed there to avoid wrong colors, but should not trigger for users.

Can you check the content of the local installed *.json files please?
Are they identical to the source here on GitHub?
(Not the one from your sources, the locally stored ones in your profile.)

If you self compile more than 5 days ago, longer definition files (e.g. vanilla_id.json) could get corrupted during update.

**Comment by EtlamGit** [comment]
@BrunoRMolina any changes?

**Comment by BrunoRMolina** [comment]
sorry but where can i find those .json files? i dont see then at build folder

**Comment by mrkite** [comment]
They're in the definitions folder, they're bundled into a resource that's compiled into the executable.

https://github.com/mrkite/minutor/tree/master/definitions
https://github.com/mrkite/minutor/blob/master/minutor.qrc

**Comment by EtlamGit** [comment]
In case you are searching the "local" .json files, then they are stored in your user profile folder.
These are used when Minutor is running. They are copied there from the build at first start.

**Comment by BrunoRMolina** [comment]
Thank you, they are at  ~/.local/share/seancode/Minutor,  I deleted folder and launched minutor again and it worked, this recreat those files at process, but when i use files copied from the build the program wont start

**Comment by EtlamGit** [comment]
In the source these files have human readable names, in the "local" folder they use a hash as name. Maybe this is a problem? You have to modify/replace the files content, but keep these strange names.

Please update your local source to the latest git master version from here.
Then we can be sure there is no auto update error.

**Comment by mrkite** [comment]
Man, I really need to come up with a better way to handle these definition files.  I tried to make it all automatic and hidden, but that does make it a pain if there's actually a problem.

Lately I've been thinking that building a definition editor directly into Minutor is the best solution.  Complete with import/export abilities.

**Comment by EtlamGit** [comment]
@BrunoRMolina any changes? Still a valid issue?
I will close it otherwise...
