### ISSUE TITLE
Feature: Use accellerator keys for variable scrolling speed

### ISSUE THREAD

**Issue by Metibor** [mrkite/minutor#109]
When using the arrow keys for scrolling, it would be nice if you can use some accellerator keys to change the size of the steps (and be faster than dragging the map with the mouse).
Currently the step size is 10 blocks.

Suggestion:
Unmodified: Change from 10 to 16 blocks per step (1 Chunk)
SHIFT: 1 block per step for fine positioning (yes, I need it sometimes)
CTRL: 128 blocks per step (8 Chunks)
ALT: 512 blocks per step (1 Region)

**Comment by mrkite** [comment]
Huh.  I could've sworn it did this already, but apparently not.  It's simple enough to add, so I'll add it.
