### ISSUE TITLE
Feature: Go to Coordinate/Chunk/Region

### ISSUE THREAD

**Issue by Metibor** [mrkite/minutor#110]
On a big map, it would be nice to use CTRL+G to get a window, where you can put in some coordinates, a chunk number or a region to get faster to a known position.

UI could be a little bit similar to [https://dinnerbone.com/minecraft/tools/coordinates/](url)

**Comment by EtlamGit** [comment]
You can set the position once at startup:
https://github.com/mrkite/minutor/wiki/Command-Line

Not exactly what you would like to have, but helpful for some cases.

**Comment by Metibor** [comment]
I'll check it out, but of course an In-App-Solution locations would be more convenient. :)

**Comment by Metibor** [comment]
Hi there, I have started to work on this. See [here](https://github.com/Metibor/minutor/commit/0eddf7a7ee5c5a56bd457b451f078d4415d979e8).
There is still some logic missing (i.e. automatic adaption of the values in the different spin boxes), but I think I am on the right path.
Putting some values into Block X/Z and pushing the button ist already working.
