### ISSUE TITLE
2.1.2 shows air blocks in a reddish color

### ISSUE THREAD

**Issue by BigAlanM** [mrkite/minutor#119]
When I load a world the display goes to a "sort of" red and to see anything I have to lower the view below ground level to see anything meaningful.
When I place the cursor on one of these red blocks the text display says Air (0,0).
I'm assuming that this is "cave mode" but the Cave Mode selection in View is in grey and Ctrl-C does not do anything.
I'm running under Windows 10 OS and have tried Minutor 2.1.2 with MCJE 1.9  and 1.12 worlds.
Unless I'm missing it I can't find where the color for an Air block (0,0) is defined.

**Comment by BigAlanM** [comment]
I resolved the problem.
It seems that the .exe release doesn't contain the latest definition files.
I exported all four definition packs and compared them to the four .json in https://github.com/mrkite/minutor/tree/master/definitions and 3 of the 4 were out of date.
Only the dimension .json was the same.
After updating the packs this version works well with MCJE 1.12.1 worlds and, I assume previous version worlds.

**Comment by BigAlanM** [comment]
I've posted instructions on how to update the definition packs in
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1260549-minutor-osx-linux-windows-2-0-1?page=42  
Post # 827.

Note that all .json source files have "Vanilla" as the pack name.  My instructions indicate to change the files to give the packs as displayed in the Definitions dialog box meaningful names.

**Comment by EtlamGit** [comment]
That behavior is very strange! Release 2.1.2 contains definitions that are sufficient for 1.12 worlds. Later changes are more of cosmetic nature (name of Terracotta and bug with Ocelots).
I would assume that you had older definition files on disk and installed 2.1.2 on top of that. Maybe something went wrong in that scenario...?

Do you remember what version number was inside your (not working) definition files?

**Comment by EtlamGit** [comment]
@BigAlanM can we close this issue? Or is there something left we could investigate?

**Comment by BigAlanM** [comment]
Yes,  After I sorted out the various definition packs and found the latest one (with the same date in the .json but different content) 2.1.2 works fine.
Thanks.

**Comment by EtlamGit** [comment]
Nevertheless, I will try to improve automatic definition update handling in the future...
