### ISSUE TITLE
Open world button greyed out after installation on windows 10

### ISSUE THREAD

**Issue by Nemelis** [mrkite/minutor#124]
I've recently bought a new computer with windows 10.
After installation of minutor I had to set it to run as window 7 application, else it could not start.

Almost everything is working fine, only the Open World menu is greyed out, so I have to select my minecraft saves using the Open menu item.

Some details:
Both minecraft and minutor are in their own directories in I:/program files(x86)
Minecraft savefiles are store in the usual location (%appdata%/.minecraft/saves)

What you see is (see attached file):
![greyed_out_open_world](https://user-images.githubusercontent.com/35840579/35442379-5fb9a95e-02a7-11e8-9fb2-aec740c820e6.JPG)

**Comment by Nemelis** [comment]
issue resolved itself after setting the Default location in settings and toggling the 'use Default Location' button a few times.

**Comment by BigAlanM** [comment]
Yep, Use Default Location needs to be checked and the full path to the .minecraft folder.
