### ISSUE TITLE
Grass is grey?

### ISSUE THREAD

**Issue by philipwhiuk** [mrkite/minutor#126]
https://github.com/mrkite/minutor/blob/ececca1d7cde33e353be8259d129b6f1b0fa47ae/definitions/vanilla_ids.json#L54

Seems like an odd choice.

**Comment by philipwhiuk** [comment]
Seems fine in latest release. Closing.

**Comment by EtlamGit** [comment]
Yes, gray is the intended color for Grass and Leaves...
The rendered color is Biome dependent like in the game.
