### ISSUE TITLE
Building on OSX out of date instructions?

### ISSUE THREAD

**Issue by karlbunch** [mrkite/minutor#135]
I tried to follow the qt build instructions and it fails (see below).  Searching around qt sites its not clear what is wrong.

How are others building minutor on OSX?  I'm trying to test the m1.13 branch on OSX.

FYI: macOS Sierra 10.12.6

```
$ perl init-repository --module-subset=default,-qtwebkit,-qtwebkit-examples,-qtwebengine
...[removed pages of output]...
Aliasing /Users/karl/WKA/qt5/qtrepotools/git-hooks/gerrit_commit_msg_hook
      as qtxmlpatterns/.git/hooks/commit-msg ...
Aliasing /Users/karl/WKA/qt5/qtrepotools/git-hooks/git_post_commit_hook
      as qtxmlpatterns/.git/hooks/post-commit ...
$ git checkout 5.5
warning: unable to rmdir qtcharts: Directory not empty
warning: unable to rmdir qtdatavis3d: Directory not empty
warning: unable to rmdir qtgamepad: Directory not empty
warning: unable to rmdir qtnetworkauth: Directory not empty
warning: unable to rmdir qtpurchasing: Directory not empty
warning: unable to rmdir qtquickcontrols2: Directory not empty
warning: unable to rmdir qtremoteobjects: Directory not empty
warning: unable to rmdir qtscxml: Directory not empty
warning: unable to rmdir qtserialbus: Directory not empty
warning: unable to rmdir qtspeech: Directory not empty
warning: unable to rmdir qtvirtualkeyboard: Directory not empty
warning: unable to rmdir qtwebglplugin: Directory not empty
warning: unable to rmdir qtwebview: Directory not empty
M	qt3d
M	qtactiveqt
M	qtandroidextras
...[removed output]...
M	qtxmlpatterns
Branch 5.5 set up to track remote branch 5.5 from origin.
Switched to a new branch '5.5'
$ ./configure -prefix $PWD -opensource -confirm-license -nomake tests -nomake examples -release -static
+ cd qtbase
/Users/karl/WKA/qt5/qtbase
+ /Users/karl/WKA/qt5/qtbase/configure -top-level -prefix /Users/karl/WKA/qt5 -opensource -confirm-license -nomake tests -nomake examples -release -static
<srcbase> = /Users/karl/WKA/qt5/qtbase
<bldbase> = /Users/karl/WKA/qt5/qtbase
<outbase> = /Users/karl/WKA/qt5/qtbase
Creating qmake...
...............................................................................................Done.
Info: creating super cache file /Users/karl/WKA/qt5/.qmake.super
/Users/karl/WKA/qt5/qtbase/mkspecs/features/resolve_config.prf:25: 'addExclusiveBuilds' is not a recognized test function.
/Users/karl/WKA/qt5/qtbase/mkspecs/features/resolve_config.prf:37: 'addExclusiveBuilds' is not a recognized test function.
/Users/karl/WKA/qt5/qtbase/mkspecs/features/qt_docs_targets.prf:31: 'prepareRecursiveTarget' is not a recognized test function.
/Users/karl/WKA/qt5/qtbase/mkspecs/features/qt_docs_targets.prf:31: 'prepareRecursiveTarget' is not a recognized test function.
/Users/karl/WKA/qt5/qtbase/mkspecs/features/qt_docs_targets.prf:31: 'prepareRecursiveTarget' is not a recognized test function.
/Users/karl/WKA/qt5/qtbase/mkspecs/features/qt_docs_targets.prf:31: 'prepareRecursiveTarget' is not a recognized test function.
/Users/karl/WKA/qt5/qtbase/mkspecs/features/qt_docs_targets.prf:31: 'prepareRecursiveTarget' is not a recognized test function.
/Users/karl/WKA/qt5/qtbase/mkspecs/features/qt_docs_targets.prf:31: 'prepareRecursiveTarget' is not a recognized test function.
/Users/karl/WKA/qt5/qtbase/mkspecs/features/qt_docs_targets.prf:31: 'prepareRecursiveTarget' is not a recognized test function.
/Users/karl/WKA/qt5/qtbase/mkspecs/features/qt_docs_targets.prf:31: 'prepareRecursiveTarget' is not a recognized test function.
/Users/karl/WKA/qt5/qtbase/mkspecs/features/qt_docs_targets.prf:31: 'prepareRecursiveTarget' is not a recognized test function.
Unknown generator specified: DUMMY
(arg: 12) ./configure -prefix $PWD -opensource -confirm-license -nomake tests -nomake examples -release -static
```

**Comment by karlbunch** [comment]
Ok a bit closer but still fails:

```
$ git clone -b 5.5 https://code.qt.io/qt/qt5.git
$ cd qt5
$ perl init-repository --module-subset=default,-qtwebkit,-qtwebkit-examples,-qtwebengine
# Patch for later versions of xcode
$ sed -i '' -e 's/-find xcrun/-find xcodebuild/' qtbase/configure qtbase/mkspecs/features/mac/default_pre.prf
$ ./configure -prefix $PWD -opensource -confirm-license -nomake tests -nomake examples -release -static
$ make -j$(sysctl -n hw.physicalcpu)
$ cd minutor
$ ~/qt5/qtbase/bin/qmake
ld: library not found for -lqcocoa
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [minutor.app/Contents/MacOS/minutor] Error 1
```

**Comment by karlbunch** [comment]
Works if you use the Qt Downloader:

- https://www.qt.io/download
- Choose "Open Source" -> Hit [Download]
- Run Installer
- Choose qt5.5
- Wait a while (3Gb Download)

```
# Patch for later versions of Xcode
$ sed -i '' -e 's/-find xcrun/-find xcodebuild/' ~/Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf
$ cd minutor
$ ~/Qt/5.5/clang_64/bin/qmake
$ make -j$(sysctl -n hw.physicalcpu)
```

**Comment by karlbunch** [comment]
Also I can confirm that branch m1.13 when built as above will load 1.13 maps with all the limitations that are already known and documented in #125

**Comment by AdriaanRenting** [comment]
If I clone the git m1.13 branch and then open the .pro in Qt Creator and build with clang and Qt 5.5, on MacOS 10.13.6, then I do get a working executable. I have no problem building it.

It crashes after a while though. I'll report that somewhere else.

**Comment by zieroh** [comment]
> Also I can confirm that branch m1.13 when built as above will load 1.13 maps with all the limitations that are already known and documented in #125

I was able to build a 1.13-compatible version of minutor with the help of your directions. Thanks!

**Comment by didaquis** [comment]
> I tried to follow the qt build instructions and it fails (see below)

Same situation for me.

**Comment by EtlamGit** [comment]
> > I tried to follow the qt build instructions and it fails (see below)
> Same situation for me.

Others were able to build and also left detailed instructions how to do so on MacOS.
So you have to provide a more detailed error description before someone is able to help...

**Comment by didaquis** [comment]
@karlbunch Can you send me or provide a copy of your application compiled?

**Comment by AdriaanRenting** [comment]
I have uploaded the file I built a month ago:
http://s000.tinyupload.com/?file_id=33651605807376050459

I haven't tried to build from the commandline. I just got the branch from Github, load the .pro into Qt Creator, and click the build button. That got me a working minutor.app

Qt 5.5.0, clang, Qt Creator and such, I had already setup on my machine, as I need those for work.

**Comment by didaquis** [comment]
> I have uploaded the file I built a month ago: 

Not working on my machine  :-( 
```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/minutor.app/Contents/MacOS/minutor
  Reason: image not found
```

**Comment by bskendig** [comment]
The OSX build instructions at https://github.com/mrkite/minutor/blob/master/README.md fail for me with the same `Unknown generator specified: DUMMY` error that @karlbunch reported above. I tried the "Patch for later versions of xcode" `sed` line, but then building fails again with the same error. I also tried Karl's recommendation to install QT, but the QT installer gets stuck in a loop where it tells me that I need to have Xcode 5 installed and then it tells me that I need to have Xcode 8.2 installed and it keeps repeating those two errors until I kill it. (I have Xcode 10.1 installed.)

**Comment by didaquis** [comment]
Will be nice if core team of Minutor do an official release before 1.14 be launched.

**Comment by AdriaanRenting** [comment]
> > I have uploaded the file I built a month ago:
> 
> Not working on my machine :-(
> 

I've made another attempt, trying to fix the issue:

http://s000.tinyupload.com/index.php?file_id=05573089924476039920

Usually I only work on applications that need to run on Linux, so I'm not familiar with how to deploy Qt applications for Mac, even though I run a Mac myself. :-/

**Comment by didaquis** [comment]
Can anyone try to compile using Qt 5.9.x ?

**Comment by EtlamGit** [comment]
Qt 5.9.4 and Qt 5.9.7 are working fine (on Windows 7), Qt 5.12.0 is currently not working.

**Comment by bskendig** [comment]
Has anyone been able to successfully build Minutor for Windows or macOS? If so, could you put your build online somewhere that people can get it?
I hope that the Minutor maintainer will soon update the downloads on http://seancode.com/minutor/ to versions that work with Minecraft 1.13.

**Comment by EtlamGit** [comment]
Windows builds are working fine with Qt 5.9.7 and the instructions from the Wiki: [Prerelease 2.2.0](https://www.dropbox.com/s/p4ra0cpejgr4vdt/Minutor-2.2.0-etlamgit.7z?dl=0)

**Comment by mrkite** [comment]
I updated the instructions for Mac OS.   Was able to do a static build of Qt 5.12 and successfully link against it.  Check the wiki.

**Comment by didaquis** [comment]
Is there a compiled version for Mac available? I can't compile the software on my machine ☹️

**Comment by mrkite** [comment]
There will be soon.

**Comment by bskendig** [comment]
There's still a problem with the macOS build instructions (at https://github.com/mrkite/minutor/wiki/Self-Compile):

```
$ git clone https://github.com/qt5.git
Cloning into 'qt5'...
remote: Not Found
fatal: repository 'https://github.com/qt5.git/' not found
```

Should the URL be https://code.qt.io/qt/qt5.git instead?

**Comment by mrkite** [comment]
Not sure how that happened..  fixed it.  It should've been
https://github.com/qt/qt5.git
