### ISSUE TITLE
Minutor keeps crashing for seemingly no reason ?!

### ISSUE THREAD

**Issue by scarletwolf134** [mrkite/minutor#139]
I'm following all the instructions one of my friends gave me like I'm doing the same exact thing they are but when i open my world it doesn't even load like the instant I click my worlds name it crashes with no explanation. Please help me I'm used to playing Minecraft on PS3 where the map shows the entire world and it's nearly impossible for me to play on PC where it only shows a portion on each map because I have terrible memory! my minecraft version is 1.13 I saw a couple of answers with the same thing but i didn't understand them and they didn't help please don't mark as a repeat and help!

**Comment by jamesmule** [comment]
Unfortunately, the format of Minecraft worlds changed with the 1.13 update, people are still in the process of updating Minutor to that format. It's possible to get a working version by building Minutor from the source code for yourself, but there is release for 1.13 worlds yet, as the creator doesn't have sufficient time at the moment and the latest version may still need some polishing.

**Comment by EtlamGit** [comment]
> on PS3
console verions of Minecraft are not supported by Minutor

> play on PC
Windows 10 version is the same than the console version
You have to use Java Edition (the first Minecraft variant from Mojang)

> terrible memory
You need some more memory and a 64 bit Windows/Linux/Mac operation system to display larger maps on larger monitors. If you only have below 4GByte or a Windows 32 bit PC than leave the window of Minutor small. 

> crashes with no explanation
Start Minutor from command line (start cmd.exe in folder of Minutor, then type minutor.exe). This may give some debug information.
Maybe your definition files are corrupt. Delete the current definitions and restart Minutor.

**Comment by EtlamGit** [comment]
Hi @scarletwolf134, any progress on your issue?
Maybe you can take a look to #143 also?

**Comment by BozoKenobo** [comment]
(Windows 10, Minecraft Java Ed 1.13.2)

I'm having the same problem:
When attempting to open any of my worlds (they're all 1.13.2), Minutor crashes immediately.
I tried running from cmd, but the problem isn't opening Minutor, its opening the world, so cmd doesn't give me any debug info.  Unless, I'm doing something wrong, which is certainly possible.

I've looked at the tutorials on how to compile my own, but they're beyond me.
Do I just need to wait until the version for 1.13 is done, or is there something else going on?

Thanks in advance for any input.

**Comment by EtlamGit** [comment]
Last official Release of Minutor is not able to load the new 1.13 data structures, as they have been changed completely. So you have to wait for the upcoming release.

**Comment by BozoKenobo** [comment]
Understood.  Thanks for helping a noob! :)

**Comment by richardwhiuk** [comment]
https://github.com/mrkite/minutor/releases/tag/2.2.0 has been released

Thanks! 😄
