### ISSUE TITLE
Feature request: Restore location after reload and add Y to status bar.

### ISSUE THREAD

**Issue by cpforbes** [mrkite/minutor#141]
After reloading (F5) I want the view to return to the location instead of jumping to the spawn point.
I want the block's Y coordinate in Statusbar in addition to the X and Z.

I will have a pull requests with these changes soon.

**Comment by jamesmule** [comment]
Related to that, maybe it's a good idea to combine the Refresh from View and Reload from File into a single action?

**Comment by EtlamGit** [comment]
The intended way to achieve this is to press F2 (Menu VIEW->REFRESH).
And yes it is intended to have2 separate methods to achieve to different results.

I agree that having Y coordinate might be useful.

**Comment by cpforbes** [comment]
Thanks for merging the change.
