### ISSUE TITLE
NULL pointer memcpy while loading chunk

### ISSUE THREAD

**Issue by torteshui** [mrkite/minutor#143]
In Chunk::load, line 62, biomes->toIntArray() can become NULL under unknown circumstances and subsequently cause the following memcpy to crash. A simple check before the memcpy avoids the crash.

Further info: The world was converted from 1.12.2 to 1.13 (now 1.13.1) with setting the repop flag on some water chunks (which simply causes them to be regenerated in 1.13). The affected chunks might be some of those and/or have not been explored again in 1.13. Other such chunks load just fine, though.

Edit: Some more investigation revealed that the affected chunks report an "Unknown" biome with "Unknown" or valid blocks. Chunks with "Unknown" blocks, but valid biome do not seem to cause a crash.

**Comment by jamesmule** [comment]
See newest comments in #125, the Biomes NBT tag in chunks is an int array in 1.13, but a byte array in older chunks. Since Tag_ByteArray doesn't have a toIntArray(), it uses the one from its base class Tag, which returns null. Exploring those chunks does indeed fix that by converting it to an int array.

**Comment by EtlamGit** [comment]
Could you provide the non-working region file?

**Comment by jamesmule** [comment]
We can just fix it, since we know exactly what's causing it, either with a simple null check of toIntArray or by checking the Tag type somehow or using polymorphism. I don't feel that comfortable with C++ yet, so I'm not sure I can do it myself.

**Comment by torteshui** [comment]
I should have read the comments in #125 before, would have saved me some debugging time :-)

Anyway, here are 4 region files, at least one of them causes the issues. Sorry for the big file...

[mca.zip](https://github.com/mrkite/minutor/files/2461065/mca.zip)

My "fix" is a simple robustness check as suggested by jamesmule:

    const qint32 *intArray = biomes->toIntArray();
    if (intArray) memcpy(this->biomes, intArray, sizeof(int)*biomes->length());

Of course this doesn't solve anything, but since it should only happen with some unexplored areas, it might be enough?

**Comment by EtlamGit** [comment]
@jamesmule fixing this NULL pointer issue is indeed simple.

But I am interested in understanding **why** this is happening in Minecraft. If there is a bigger conversion bug in Minecraft, we may have to handle other obscurities also.

I have converted several worlds from 1.12.2 to 1.13.1 without ever encounter this problem. So there must be something different in what you did compared to what I did. I used only vanilla Minecraft, deleted some complete regions, used NBTExplorer to modify some Structures and let the conversion happen during traveling with Minecraft 1.13.1. So I have a world with mixed Chunks in 1.12.2 and 1.13.1 (maybe also some older ones) and Minutor works fine with that.

**Comment by jamesmule** [comment]
I used the Optimize World feature in the world settings to convert my worlds before loading them, that might explain it.

**Comment by EtlamGit** [comment]
@jamesmule exactly these 3 additional bugs I found some minutes ago were the reason for using a real region file and not an artificial one with only one bug present.

**Comment by jamesmule** [comment]
@EtlamGit yeah, sorry about that, I was expecting it to be just a bug in Minecraft's conversion code

**Comment by AdriaanRenting** [comment]
[Minutor_problems.zip](https://github.com/mrkite/minutor/files/2463710/Minutor_problems.zip)

Here are the 4 region files I have encountered that caused the problem.

NTBExplorer also has trouble with these files and crashes when I try to look at some of the chunks.

The world was generated after 1.12, with some custom settings, that I think should not affect things, just a few adjustments to spawn rates of blocks. No editing or anything has taken place, it's a vanilla 1.12 world, converted (partially) to 1.13.

**Comment by AdriaanRenting** [comment]
<img width="353" alt="screen shot 2018-10-10 at 10 17 07" src="https://user-images.githubusercontent.com/20068104/46722428-bda8db00-cc75-11e8-8849-2bfc93755d0c.png">
<img width="348" alt="screen shot 2018-10-10 at 10 17 18" src="https://user-images.githubusercontent.com/20068104/46722433-c00b3500-cc75-11e8-9f88-1a582c1568bf.png">
NTBExplorer doesn't seem to support copy-paste, so I can only make a screenshot of the custom settings.

**Comment by AdriaanRenting** [comment]
I will test tonight if #144 fixes my problems.

**Comment by torteshui** [comment]
The changes from #144 fix my problems - thank you :-)

**Comment by EtlamGit** [comment]
Hi @AdriaanRenting, I see a mixture of 1139 (1.12) and 1628 (1.13.1) version Chunks in your region files.
Minutor loads all 4 region files completely without any problems.

Some interesting observation is that you also have IntArrays for Chunks with Status==empty. It seems that Minecraft has/had some conversion issue here. But our code is prepared for that...


With NBTExplorer 2.8.0 I do not get crashes. Which Chunk did you experience problems?

**Comment by AdriaanRenting** [comment]
#144 seems to have fixed things for me. The minutor I compiled with the current m1.13 branch loads my world just fine without crashing.

**Comment by AdriaanRenting** [comment]
> With NBTExplorer 2.8.0 I do not get crashes. Which Chunk did you experience problems?
The Mac version is stuck on 2.0.3
I now found that that only works with worlds up to 1.12, not 1.13
