### ISSUE TITLE
Visualize dungeons as structures

### ISSUE THREAD

**Issue by madmaxoft** [mrkite/minutor#146]
Despite not being recorded in the structures, it would be nice to have dungeons visualized similarly, so that they are easier to find.

This could be done as a heuristic in the chunk loader - if the loaded chunk contains a mob spawner, check the block underneath it, if it's a mossy cobblestone, add a dungeon entry in the structures array.

Alternatively, this could visualize all mob spawners, since they could be a valuable target.

**Comment by EtlamGit** [comment]
Interesting idea.
- How would you estimate the covered area?
- Have you ever tried to find one of these tiny Igloo?
- What metadata would you like to show on double click?

**Comment by madmaxoft** [comment]
Thinking about this a bit more, I think visualising each and every mobspawner would be beneficial, without any distinction whether it's a dungeon or something else.
- Covered area: Don't estimate anything, just use a fixed-size radius with which the structure overlay is visible
- Igloo: never found one. Is there a mobspawner? Or what's the relevance?
- Metadata: (no idea we had dblclick info :) At the very least, the mobspawner's coords. Ideally, the kind of entities it spawns (including multi-entity spawners that can be inserted by commands), perhaps some heuristic about the surroundings could provide a hint about the kind of structure it's in.

**Comment by EtlamGit** [comment]
Igloo was just an example of a Structure with very very small radius. The same than Witch Hut and Dwell. Nearly impossible to locate on the map...

**Comment by madmaxoft** [comment]
I suppose that's more of a rendering problem than the actual detection / parsing problem. I've had trouble locating a jungle temple on a map that I knew was there. This could be solved with some extra logic in the renderer - if the structure to be rendered is too small, enlarge it temporarily and don't use round corners.

**Comment by EtlamGit** [comment]
Hi @madmaxoft ,

I started to work on this feature.
You can test the current progress in [my branch](https://github.com/EtlamGit/minutor/tree/show-spawners-as-overlay).
* minecraft:spawner is a Block Entity (also known as Tile Entity). This is something different than Structures, but I decided, that it matches the other Structures we have as Overlay.
* minecraft:chest can be parsed exactly the same way, but it makes no sense to put that into Structure Overlay also. I still think about a good place to put them. Maybe it is just to display the properties dialog when doing a double click.

**Comment by EtlamGit** [comment]
Putting the minecraft:spawner into the Structures looks like this example. All spawners are represented by a single overlay item.
![grafik](https://user-images.githubusercontent.com/5821779/145072373-47e0df0a-c425-40f8-acdd-51e375d51926.png)

An alternative solution would be to add a third category, allowing to separate spawners by Mob type:

[Structure Overlays]
...
[Spawner Overlays]
minecraft:zombie
minecraft:skeleton
minecraft:cave_spider
minecraft:blaze
[Entitiy Overlays]
...
This would make the Overlay menu even longer, maybe too long in case of custom maps and mods installed.

**Comment by madmaxoft** [comment]
I think a single menu item is ideal.
