### ISSUE TITLE
builds with Qt 5.12.0 are not working

### ISSUE THREAD

**Issue by EtlamGit** [mrkite/minutor#149]
It seems that Qt 5.12.0 (or some other version between LTS 5.9.7 - 5.12.0) has changed the behavior of qHash(QString). We get multiple different results when hashing the definition file name. And therefore start to pollute the folder `%localappdata%/seancode/Minutor/`.

Solution: stick to LTS 5.9.x for the moment.

**Comment by didaquis** [comment]
Maybe is related to https://github.com/mrkite/minutor/issues/135 ???

**Comment by didaquis** [comment]
https://doc.qt.io/qt-5.9/qhash.html  vs https://doc.qt.io/qt-5/qhash.html

**Comment by EtlamGit** [comment]
Reason found: Qt 5.12 changed this file [qhash.cpp](https://code.woboq.org/qt5/qtbase/src/corelib/tools/qhash.cpp.html)
Now the CPU build-in crc32 is only called if you give an initial seed that is not zero.

CPU build-in crc32 calculation is available on AMD/Intel CPUs with [SSE4.2](https://de.wikipedia.org/wiki/Streaming_SIMD_Extensions_4). This means for CPUs manufactured in the last 10 years. Results from this CPU build-in crc32 calculation is different from the alternative hash function used otherwise.

One solution would be to give a seed. But this still breaks first start with new Minutor version as the old files get duplicated.

**Comment by EtlamGit** [comment]
@didaquis @mrkite please review the proposed solution
