### ISSUE TITLE
So, when is compatibility with 1.14 coming?

### ISSUE THREAD

**Issue by archiesholland** [mrkite/minutor#156]
(ducks when EtlamGit and mrkite start throwing things)

Seriously, thank you, guys!

**Comment by EtlamGit** [comment]
Is 1.14 out already?

I planned to start with the definition files in next vacation period, which is Easter break.
Hopefully there is no complete storage overhaul again...

**Comment by archiesholland** [comment]
Only pre-release snapshots, so I was just kidding....I think the changes are all cosmetic (new NPC mobs, new structures, new weapons, things like that...)

Oh, and I'm Ashtoo on the Minecraft forums.
