### ISSUE TITLE
Unknown biome 2.1 (minecraft 1.13.2)

### ISSUE THREAD

**Issue by Bennink** [mrkite/minutor#158]
Whenever I open a word, it doesn't load. It stays on a square grid and says unknown biome. I'm using the latest version of both Minecraft and Minutor from the day of this post.

**Comment by EtlamGit** [comment]
Please check your local definition files. (Some hints how to find them are in #107 #157)

It is save to delete the *.json files. They are recreated on next start of Minutor.

**Comment by EtlamGit** [comment]
Any update on this issue?

**Comment by jamesmule** [comment]
Looks like I'm experiencing the same issue on the latest commit.

Minutor redownloads the definition files into the AppData folder on startup if there aren't any yet but doesn't add them to its definition list. Only when I manually add definition files are those added to the definition list and copied into the AppData dir. Those manually added files have to have a different name or type than the other files though, you get a copy error message if they don't.

Two other things, first, the Check for updates button doesn't seem to work, it doesn't redownload any definitions into AppData after I deleted them when Minutor was already open.

Second, there is an error message box I get when trying to overwrite existing AppData definitions ("Copy error"). It's not terribly descriptive and probably shouldn't appear at all. I think it'd be better if Minutor asked for a confirmation there if a definition with the same type and name is already present.

**Comment by madmaxoft** [comment]
I think #163 should fix this for you, at least partially (it allows you to add the definition files properly).
