### ISSUE TITLE
Add warning about "no definitions" to UI

### ISSUE THREAD

**Issue by madmaxoft** [mrkite/minutor#164]
When there are no definitions, loading a world seems to work fine but nothing is displayed and the user is left clueless about what went wrong. Instead, the UI should show some warning along the lines of `There are no definitions loaded, manage them here`, (ideally clickable, taking them to the definition manager window).

Alternatively, when Minutor detects that there are no definitions selected, it should load the built-in defaults.

**Comment by EtlamGit** [comment]
The new method checkAndRepair() should handle exactly that case. It is called before loading definitions. And afterwards at least the build-in definitions are available. You might want to test & review the new code.
(There was an error in the last implementation...)

**Comment by EtlamGit** [comment]
@madmaxoft did you find some time to test if the new repair code works in all of your scenarios?

**Comment by madmaxoft** [comment]
I'll have to check again, I have seen some problems, but don't know if the computer was running the latest code.

**Comment by madmaxoft** [comment]
It seems to be alright now.

For some reason I had two files with block type definitions, one for 1.13, the other for 1.14, somehow both were stored in the registry as active. This resulted in the chain of error messages. However, after removing all the files from the appdata folder, Minutor recovered.
