### ISSUE TITLE
Debian version crashes on loading Java 1.14 world

### ISSUE THREAD

**Issue by Tarliman** [mrkite/minutor#165]
Running MX Linux 17, latest patch revisions. Installed Minutor Debian package. Minutor opens without complaint. Used Settings option on help menu to point to my Minecraft_1.14/game subfolder. Open World menu pops out daughter menu showing the two worlds I have created on the local drive. When I select Test02, the survival mode world, Minutor crashes without displaying an error message. I see no entries in /var/log/* for minutor, and the program does not appear to have logging elsewhere.

**Comment by StrikeAgainst** [comment]
I'm running on Windows 10 Home and have the very same issue, doesn't seem to be OS related. Downgrading from the current (1.14.3) to 1.14.0 doesn't fix it either.

**Comment by BigAlanM** [comment]
It does seem strange that Minutor works fine on a 1.13 .2 world but doesn't on a 1.14 world.

**Comment by EtlamGit** [comment]
Are you using Minutor official release or a self build one?
Because here everything is fine with Minecraft 1.14.3 and a build from trunk.

**Comment by Tarliman** [comment]
I'm using the .deb downloaded from Minutor github and installed with no customization. This is a brand new install. My Minecraft is vanilla, no mods. EltamGit, what OS are you running under? Are you suggesting I should pull from git and build on my platform rather than installing the .deb?

**Comment by EtlamGit** [comment]
I'm using Minutor only on Windows, but I assume the .deb package contains the "pre-build" release version. This would explain your problems, as they are fixed in trunk.
You could build your own executable or wait for the next release.
@mrkite we should do a release soon. I noticed no problems with current trunk, but will do tests with more worlds this weekend.

**Comment by mrkite** [comment]
If @Tarliman can pull from git and verify it works for him, I'll go ahead and update the linux release.

**Comment by PopotaPlay** [comment]
Same problem here... using .msi and noinstaller versions...

**Comment by EtlamGit** [comment]
It is known and fixed, that the official release is not compatible with 1.14 upwards. Mojang changed again details in the storage format.
Pull Request #159 has changed that but is not released now.

**Comment by FreshLine** [comment]
can you realease the updated version please

**Comment by StrikeAgainst** [comment]
Any information on when the fix goes live?

**Comment by mkocsis** [comment]
It took few extra tool installs, but I did get the source code to compile, looks like my 1.14.2 maps do load correctly on Windows 10. The Structure Overlays and Entity Overlays aren't complete, but it's really nice to have the base Minutor functional. Let me know if there's any development or testing I can help out with.

**Comment by EtlamGit** [comment]
Can you explain in more detail, what Overlays are not working?
The Overlay menu should automatically add all Entity types and Structures found during loading the Chunks. So there should be no situation with missing Structures...

**Comment by StrikeAgainst** [comment]
@mkocsis Would you be able to share your compiled version with us so we have something working in the meantime? I'm not able to compile it myself...

**Comment by Calder2019** [comment]
Waiting for the result compiled version to support the 1.14.x chunks.

**Comment by EtlamGit** [comment]
[Windows Nightly](https://github.com/mrkite/minutor/wiki/Nighlty-Builds)

**Comment by StrikeAgainst** [comment]
Oh, I had no idea there was a nightly build, and it actually works just fine! Thank you :)

**Comment by kdbertel** [comment]
Any chance we can also get a nightly for macOS builds?

**Comment by didaquis** [comment]
> Any chance we can also get a nightly for macOS builds?

+ 1

**Comment by Kolcha** [comment]
Unofficial Nightly builds
------------------------
build from master branch, commit https://github.com/mrkite/minutor/commit/c7d32fa8a10a7d055341c002a13451a04c074d59 + modifications from https://github.com/mrkite/minutor/pull/203
- [Windows](https://www.dropbox.com/s/k3vddwqjetqm6r8/minutor-win64.zip?dl=1), x64, Qt 5.12.6, no installer
- [Linux](https://software.opensuse.org//download.html?project=home%3Anikoneko&package=minutor), x64, Debian 10+/Ubuntu 18.04+, custom repo (like PPA)
- [macOS](https://www.dropbox.com/s/tyhbe9k2q7517mn/minutor-macosx.dmg?dl=1), minimum 10.12 (Sierra), Qt 5.12.6

supports Minecraft 1.14.4, maybe even 1.15.1 (not tested). everything was tested only on macOS.

**Comment by didaquis** [comment]
I'm on a Mac and I tried your macOS build. Seems like is not working. Run the build throws me an error: 

![Captura de pantalla 2020-01-05 a las 9 18 49](https://user-images.githubusercontent.com/6883041/71777207-fe88c000-2f9c-11ea-8787-5af3d83ec2ea.png)

**Comment by Kolcha** [comment]
looks like this a problem after upgrade... try to remove any leftovers in home directory:
```
~/Library/Application Support/seancode/Minutor/
~/Library/Saved Application State/com.seancode.minutor.savedState/
~/Library/Preferences/com.seancode.Minutor.plist
```
first directory is some app data directory which contains few .json files which purpose in unknown to me, but they can be safely deleted, they are generated again on app startup.
second directory is something generated by macOS, I really don't know what it is and how it used, but 'savedState' suffix is the reason to delete it. such folders are also automatically generated for almost any app on macOS.
the third in the list is app config file, Qt uses native APIs to save config. it is also safe to delete it, new one will be generated on app launch (or exit?).

right now I'm not familiar with app code, but I'll learn it, it will take some time. this app is interesting to me, and it does a lot of strange things which I as experienced C++ developer can't understand, I want to fix at least few of them.

**Comment by didaquis** [comment]
> try to remove any leftovers in home directory

I tested again following your instructions. Same situation   `:-(`

**Comment by Kolcha** [comment]
so... looks like a some bug... but that loaded all worlds (including newly created with 1.14.4) I have, so I decided to publish this build, but it is imperfect...

sorry, I can't help right now, I know too little about this app, and nothing about Minecraft data structures and how they saved and used by this app.

**Comment by EtlamGit** [comment]
This dialog box appears when multiple definition files are defining the same block. In case you get very much of these messages, you probably have at least 2 files with different name, but defining the same stuff. Like written, deleting definitions is save.
Never use older versions of Minutor in mixture with newer ones. This may generate duplicated definition files and you have to delete again. Latest Minutor (NOT the official Release but the Nightlies) try to clean-up most common cases of mixed-up definition files. And newer versions are always backwards compatible. So there is no reason to go back.

Yes, I know this dialog messages are annoying. But if they are happening, something severe is broken and it it makes no sense to continue. In case we are annoying enough, a issue is opened here and we might be able to help.

**Comment by didaquis** [comment]
> maybe even 1.15.1 (not tested)

It works! 

I did this again: 
```
~/Library/Application Support/seancode/Minutor/
~/Library/Saved Application State/com.seancode.minutor.savedState/
~/Library/Preferences/com.seancode.Minutor.plist
```
And then I restart the computer. And now it's working fine. 

Thank you @EtlamGit and @Kolcha for your work and help.

**Comment by Larretronix** [comment]
I just tested the Nightly build on a 1.16 snapshot world (20w08a), and it does work without crashing on that. Just needs new textures for the new blocks in the future. The nightly build recognizes the new block as "unknown - minecraft:warped_nylium", etc. Something for the future tho, as 1.16 is not going to release for a long while now. I am able to distinguish the new Nether biomes with this, so all is good.

**Comment by EtlamGit** [comment]
I will start with 1.16 definition update when some more nightly builds have past...
(Or during Easter break)
