### ISSUE TITLE
display timestamps

### ISSUE THREAD

**Issue by IronException** [mrkite/minutor#175]
minecraft saves the timestamp in which the chunk was last loaded. It would be kinda cool to see that data

**Comment by EtlamGit** [comment]
You probably have something in mind like [Regional difficulty](https://minecraft.fandom.com/wiki/Difficulty#Regional_difficulty).

What we need for that is:
* The worlds difficulty -> stored in level.dat
* The worlds total age -> probably also stored in level.dat
  But this has only an affect during the first 63 in-game-days which is gone after 1 full real-day. Could be ignored.
* Chunk inhabited time -> stored in Chunks
* The moon phase -> ? I have no idea where to get that ?
  This effect cycles all 8 in-game-days and could also be ignored.

**Comment by EtlamGit** [comment]
![grafik](https://user-images.githubusercontent.com/5821779/156416989-e0189769-17b3-40aa-926d-d908548d9395.png)
@IronException is something like this what you expected?
It is the Chunks InhabitedTime of a 1.18 world. Full red is the maximum needed for highest Regional Difficulty.

**Comment by EtlamGit** [comment]
![grafik](https://user-images.githubusercontent.com/5821779/156585973-b936177c-bab3-4086-abd6-2e55ccb6cf3e.png)
Exactly the same data, but with 6-color-mapping instead of 3-color-mapping.

* 3-color-mapping is from <none>->green->yellow->red
* 6-color-mapping is from <none>->blue->cyan->green->yellow->red->purple

**Comment by EtlamGit** [comment]
[local branch with current state](https://github.com/EtlamGit/minutor/tree/view-regional-difficulty)
