### ISSUE TITLE
display chunk borders

### ISSUE THREAD

**Issue by IronException** [mrkite/minutor#176]
next to unexplored chunks this is ofc already kinda visible but it would be awesome to see that too inside a big map. Additionally region borders could also be shown

**Comment by EtlamGit** [comment]
You can get Chunk and Region boundaries when exporting to PNG image file.

**Comment by IronException** [comment]
What do you mean? saving the map as an image? But there are no lines to show where the borders are. I would have to remove regions and stuff to see them. Or count the tiles from the background image

**Comment by EtlamGit** [comment]
![grafik](https://user-images.githubusercontent.com/5821779/64277509-cddf3e00-cf4a-11e9-9323-9d960eb8c9ec.png)

I get a checkerboard pattern for Chunks and Regions when selecting the corresponding options in the export dialog.
