### ISSUE TITLE
Add Travis / Appveyor CI

### ISSUE THREAD

**Issue by madmaxoft** [mrkite/minutor#182]
The CI should be used to detect PRs that don't even compile. Additionally, they can be used to provide nightbuilds.

**Comment by EtlamGit** [comment]
How do you setup a CI that supports Qt 5.12 ?

**Comment by madmaxoft** [comment]
Appveyor has Qt 5.12 built in. Travis supports custom build dockers, which should be able to do that, but I have no further knowledge in that area. I could ask my friends at @cuberite for help.
