### ISSUE TITLE
generate images with specific size

### ISSUE THREAD

**Issue by IronException** [mrkite/minutor#183]
I am using the save to PNG feature to make an overview of a 60 000 × 60 000 big world (the world is also getting bigger very fast). I started it yesterday but my PC crashed in the middle of the night and it was only at 30 % of generating the image.
This could have multiple reasons:

- Too many regions to load
- Too large image file
- My PC sucks

At least for the second potential cause I have a fix idea that would also be useful in general:
- Make it able to decide the size of the output image (this is similar to Issue#97: Increase zoom. So if this ever gets implemented it could be used for both)
- Let the user decide which areas should be in the output image (basically instead of putting every single chunk into the output image you can tell it two coordinates and all chunks between them are made to an image)

**Comment by madmaxoft** [comment]
Just a note, an image 60000 * 60000 blocks would need at least 9 GiB of memory (either RAM, or swap space), that could be the reason it crashed. For such a large map, I think a better solution would be to have a batch output mode which would output images, say 1024px * 1024px, that could be displayed next to each other (just like google maps).

**Comment by EtlamGit** [comment]
It is possible to define the output size! Just read the [documentation about exportsize].(https://github.com/mrkite/minutor/wiki/Command-Line)

And with an exported image you can do whatever zoom or postprocessing you want.

Regarding your really large world and export problems:
- In principle it should work!
- Minutor uses spezial code to export Chunk by Chunk to write PNGs with arbitrary size.
- The PNG is written row wise and only one Chunk at the time has to be in memory
- Maybe you hit PNGs maximum size?
- I suggest to export "smaller" parts. E.g. 16x16 regions

**Comment by ComradeCommie** [comment]
It could be possible he's running out of disk space, as 30% of a 60kx60k image would be quite big.
