### ISSUE TITLE
Making block definition packs interchangeable/more easily customizable

### ISSUE THREAD

**Issue by StrikeAgainst** [mrkite/minutor#184]
I have been exporting the vanilla block pack with the goal of changing some color/transparency attributes of certain blocks for my own purposes and have then tried to re-import the pack (not thinking of deleting the original pack), resulting in hundreds of modals popping up for every block definition of the game, telling me the specific definition was already existing. Instead of clicking through all of them I force closed Minutor and restarted it, only for it to repeat the modals.
Though I can see the point of it pointing out the exact faulty definitions, wouldn't it be less tedious to have those bundled into as few modals as possible?

Second off, I remember this tool giving the option to create customizable color definitions for blocks within the UI (back around 2012), and I'm a bit confused to see this feature gone, instead having an external pack builder feature now. I can see the advantage this gives for handling newly added blocks for Minecraft mods etc., but it comes with the prize of complicating block customization by having to alter an external JSON file while also making definition switching far more cumbersome, having to remove one pack and import another every time you want to change views - compared to just selecting a definition from the UI.
Is there any reason why the original feature was removed entirely, and are there any plans to reinstate it? If not, could I make a feature request to have multiple imported block packs interchangeable somehow?

**Comment by EtlamGit** [comment]
1) This dialog is to support a person that is changing/updating a definition file. For each error you produce, you get one message. If you like to have less messages, produce less errors.
Normal users "should" never see this dialog.
2) There is nobody to update and support non-vanilla definitions. After 2012 the application was completely rewritten, some features got lost, some new are implemented.
