### ISSUE TITLE
Minutor 2.20 suddenly throwing errors.

### ISSUE THREAD

**Issue by BigAlanM** [mrkite/minutor#187]
Minutor 2.20 has suddenly quit working on my Windows 10 machine.
I get an extremely long succession of error dialogs like the one below.
I can't close the program.
When I click on the close window X or click close another error dialog pops up.
The dialogs say "Error hashing block" at the top and

 display something like "minecraft.cave_air"
The only way I can kill this is to open Windows Task Manager, select Minutor.exe and click "End Task".

Minutor 2.12 still works properly but, of course, can't display worlds created on any release after 1.12.2.
![Minutor error](https://user-images.githubusercontent.com/5558852/65382656-63632780-dcd8-11e9-80fc-321bb699f375.jpg)

**Comment by madmaxoft** [comment]
The definitions are broken again. Please show us the listing of your definitions folder: `%localappdata%/seancode/Minutor` (usually `c:\Users\<username>\AppData\Local\seancode\Minutor`)

See #161 for info on how to fix this issue.

**Comment by BigAlanM** [comment]
![Minutor defs](https://user-images.githubusercontent.com/5558852/65392848-3ef26400-dd47-11e9-83c9-2bd0682c9f2c.JPG)

**Comment by BigAlanM** [comment]
The instructions is #161 cured my problem.
THANK YOU!!!!!
