### ISSUE TITLE
Supposed Minutor Config Problem

### ISSUE THREAD

**Issue by FriedrichDuerr** [mrkite/minutor#188]
After I started my pc today Minutor didn't work anymore. To be more exact when I execute it (cmd or normal) it doesn't open. When trying to debug the issue I saw with Search Everything that a crash file is created in "C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_minutor.exe_60e7c99ec9729874d5e1cea2566aaa3d7d7de37_a484e73c_3aa75c08-6661-4eab-a8ad-09c5aa9f69ba\Report.wer".
After each new attempt, a new slightly different folder is created with a similar file ([crashes.zip](https://github.com/mrkite/minutor/files/3764226/crashes.zip) (I attach a zip with a few of these generated crash reports in the hope that they can solve my problem)). I suppose these things are created because of windows though. 

To be able to use the program again I uninstalled and reinstalled Minutor which didn't help. Also deleting every result found in Search Everything that contained "minutor" didn't help (I even deleted "C:\Windows\Prefetch\MINUTOR.EXE-09E3415F.pf" which probably didn't even have anything to do with this).
After every reinstallment, whatever I did before, it still doesn't open and instead creates this (silent) crash report.

From a good friend I got a new debugging idea: to test Minutor on another windows user. Well, this worked but I don't have all my Minecraft settings and stuff, in general, to be able to do that. This just means that my normal profile has something somewhere that is causing minutor to silently crash.

To be honest maybe I experience a similar issue with another program. After my pc crashes the complete config file that was open at the time is overwritten with null bytes. Maybe this is what happened there. I am not completely sure wether my pc crashed last time I had Minutor open but considering these crashes happen to me daily at this point it probably did. I hope there is a "minutor" config file that is not named "minutor" and somewhere saved in a folder that is not called "minutor" and also not removed when you do remove in the installer. Please tell me there is, otherwise I have no idea how to fix this issue.

Minutor is a great tool and I use it almost daily so it is really sad I can't use it anymore. I hope there will be a way to fix this. :)

**Comment by EtlamGit** [comment]
I assume you are useing the latest release.

Try to:

- delete the folder <user>\AppData\Local\seancode\Minutor
- delete Registry settings for Minutor: HKEY_CURRENT_USER\Software\seancode\Minutor

**Comment by FriedrichDuerr** [comment]
God, thank you very much. It works again :)


Sorry, I forgot to say which version I'm using. I use it for Minecraft 1.12. So (2.2.0 6f6dc5d) threw the same errors as for some [others](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1260549-minutor-osx-linux-windows-2-0-1?page=37).

So I use version  2.1.2 fe5ccae.

**Comment by FriedrichDuerr** [comment]
Before I close this issue. I think I found a way to reproduce this issue. When installing Minutor you can use it fine. But my default location isn't enabled. When I do tho so Minutor crashes and I have the same problem as before.

I luckily am used to using Minutor with a batch (so thank you very much that I can use it again) but well yea I guess this bug still exists.

**Comment by FriedrichDuerr** [comment]
Only when I delete the registry and remove all things with the installer it works again.
Here is a picture of the settings after the installment.
![grafik](https://user-images.githubusercontent.com/54633901/67465893-5c686580-f646-11e9-8763-6ff425f73a90.png)
 When I tick "Use Default Location" two times it shows me my path and I cant open it again

**Comment by FriedrichDuerr** [comment]
[amakeMapbatchFile.txt](https://github.com/mrkite/minutor/files/3766418/amakeMapbatchFile.txt)
Somehow this batch file also doesn't work anymore. I mean it opens and stuff but it doesn't render the world. Did the commands change maybe? I tried to search the world even with opening it normally but it just showed void everywhere.

**Comment by EtlamGit** [comment]
There is currently no official release supporting the latest Minecraft versions.
But you can beta-test the [Nightly Build that is linked in the Wiki](https://github.com/mrkite/minutor/wiki/Nighlty-Builds). There is definition file repair support.

**Comment by IronException** [comment]
Yea I know. I dont need Minutor for 1.13. But it also doesn't really work for 1.12 as I stated in my latest comments. Or do they not make sense? Maybe I should move that to another issue?

**Comment by FriedrichDuerr** [comment]
Yea I know. I dont need Minutor for 1.13. But it also doesn't really work for 1.12 as I stated in my latest comments. Or do they not make sense? Maybe I should move that to another issue?

**Comment by FriedrichDuerr** [comment]
So my problem is: I use version 2.1.2 fe5ccae.
When I change the default location to actual minecraft it doesnt open anymore (like my original problem) only when deleting the data in the registry and reinstalling I can get it to open again. Problem. is: now it doesn't show any world anymore. 
https://github.com/mrkite/minutor/files/3766418/amakeMapbatchFile.txt this is a batch file I used to make a map of the world but this also doesnt work anymore. (it is a 1.12 world)

**Comment by EtlamGit** [comment]
The latest builds are completely backwards compatible (old worlds are rendered correctly). So there is no reason not to use the latest version of Minutor.

As far as I know, the "default location" bug is solved. But that can only be verified with latest builds.

Your batch file looks fine. If something is not rendered, the definition files are broken. Latest builds have auto repair and should work in all configurations.

**Comment by FriedrichDuerr** [comment]
I got it to work now. I didnt delete everything from the registry. thats probably why it didnt work. Now I can also set my default folder again

**Comment by FriedrichDuerr** [comment]
Unfortunately, I have exactly the same problem again. This time I took a picture of the ![blue screen](https://user-images.githubusercontent.com/54633901/74173276-291c0780-4c32-11ea-8af5-16bde96a8e6e.jpg)


I tried the same things I did last time but somehow I can't get it to work. I deleted everything I could but the world is not rendered anymore and after trying to update the default location I can't open the program anymore.

I deleted everything I can on my pc and in the registry before any new installation. (version 2.1.2 fe5ccae for Minecraft 1.12 like last time (I only use Minecraft for 1.12 right now and that is how I got it to work last time too)). I deleted everything I could find when I searched for **minutor** and **seancode**. I couldn't delete:
- **Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\bam\State\UserSettings\S-1-5-21-3950719445-3994068492-3964048272-1001** -> **\Device\HarddiskVolume4\Program Files (x86)\Minutor\minutor.exe**
and
- **Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\bam\State\UserSettings\S-1-5-21-3950719445-3994068492-3964048272-1001** -> **\Device\HarddiskVolume4\Users\Stephanie\AppData\Local\Temp\Temp1_minutor_noinstall.zip\minutor.exe**

**Comment by EtlamGit** [comment]
No application should be able to generate a crash of the complete operation system!

If you get a Blue Screen, something else is damaged at your computer:
+ test your RAM with [memtest](https://www.memtest86.com/)
+ check your CPU temperature
+ update all drivers for mainboard, storage and graphics card

It is not necessary to delete EVERYTHING. This might even be dangerous like the registry stuff you listed above. It is save to delete:
+ Folder: `C:\Users\<USER>\AppData\Local\seancode`
+ Registry: `HKEY_CURRENT_USER\Software\seancode`

And **always** use the latest [nightly version here](https://github.com/mrkite/minutor/wiki/Nightly-Builds). It has repair functionality inside and is backwards compatible.
