### ISSUE TITLE
Minutor "Error hashing Block"

### ISSUE THREAD

**Issue by ComradeCommie** [mrkite/minutor#193]
After zooming out in a world, Minutor crashes. Reopening the program causes the attached picture to happen. If I hold enter and go through all of the blocks, the program will eventually open but crash upon loading any world. I have tried reinstalling multiple times and deleting the seancode folder in appdata/local.
![image](https://user-images.githubusercontent.com/36094486/69694148-1bc09980-1095-11ea-93e1-889745089495.png)

**Comment by madmaxoft** [comment]
So #161 is still happening. See that issue for the possible way to fix this.
However, it would be great if you could provide us with the contents of those things (especially the registry) just before you delete them, so that we can fix it for good.

**Comment by ComradeCommie** [comment]
Got it! The folder always seems to repopulate when the program is run, so deleting them doesn't affect it. I can't attach them here so I'll share over OneDrive. https://1drv.ms/f/s!ApN5hdLpfF7TiZlUFvzrpvLbT9qTOA

**Comment by EtlamGit** [comment]
Are you using the latest build or an ancient release?

**Comment by ComradeCommie** [comment]
Both nightly and the latest official release have the same issue.

**Comment by EtlamGit** [comment]
Recent (nightly) builds should not duplicate keys. And that message box is only popping up, if you have duplicated or wrong definitions.

Try to delete Minutor folder and registry stuff like described in #161 
And use only latest Minutor afterwards.

If you still observe duplicated files or keys, please provide the names of the .json files and numbers found in the registry.

**Comment by ComradeCommie** [comment]
I did fix this by deleting registry keys, the appdata/local/seancode folder and reinstalling nightly.
