### ISSUE TITLE
search for blocks with certain id (like chests or moster spawner) and entities matching certain criterions like selling an enchanted book

### ISSUE THREAD

**Issue by cre4ture** [mrkite/minutor#199]
On my featurebranch I created a search functionality for entities and blocks. For me the feature is quite usefull to speed up search for certain blocks and entities. The results are listed in a listbox and can be displayed as an overlay item on the map. You also can sort the list according to distance.
I would like to know if you @mrkite, @EtlamGit also would be interested to have that feature on the master. I was checking if someone else also already had the need for such a search. I think #146 might be also solved by this feature, as you can just search for all the moster spawner and or chests.
Other examples would be:
- Search for diamond/gold/iron_ore
- Search for villagers that buy or sell certain items
But it will be more effort to split the feature from the other things I did there and get it onto the master.
It also brings some changes and potentially increased complexity for the threadpool and the chunkcache with it. Thats why I'm asking.

https://github.com/cre4ture/minutor-1/tree/search_enchanted_book_seller
![image](https://user-images.githubusercontent.com/252806/71001522-bf71f800-20dd-11ea-88bb-4986d59fe7fb.png)

**Comment by mrkite** [comment]
What happens if you search for something common, like stone?  Does it explode or handle it fine?

**Comment by EtlamGit** [comment]
I personally, do not need such a feature. But that is no reason, as there are many other features in Minutor that I do not "need" (or believed not to need at a first glance).
It is always bad to fork projects when not enough maintainers are available to support both branches. Therefore it would be very beneficial, if you migrate all your ideas into Minutor master. At least as long term goal.

The biggest drawback I see is when we have very specialized search dialog and then Mojang changes something. So the search should be as generic and maintenance free as possible.

As your changes will bring some intermediate instability, I suggest this approach:

* during Chistmas I try to fix the out of memory issues
* we do an official Release (with support for 1.14 and 1.15)
* after that we hopefully have some longer time where that Release works with latest vanilla Minecraft
* during 2020 we try to integrate your search feature


Issue #20 would also be solved.

**Comment by BigAlanM** [comment]
Frankly, I would love to see this.  Specifically for chests and spawners as I use Minutor to  find dungeons and portal rooms.

**Comment by cre4ture** [comment]
> What happens if you search for something common, like stone? Does it explode or handle it fine?

Your right, that's something that easily can go wrong. Currently I just put a limitation for maximum number of search results to handle this somehow. But I didn't do much testing around. So there might also be more tuning needed in this regards.
But I don't see this as a big problematic thing. There will be "relatively simple" solutions for it.
I'm more concerned about the parallelized search for speedup and the clean cancellation and stopping of this asynchronous search in every case. My current approach there works, but is difficult to maintain I guess. I have an idea of how to make it simpler, but that's also to be done.

@EtlamGit: For the block search I think its simple for maintaining. I didn't need to put specific things there which minutor isn't already relying on. You only need to translate the name into a (list of) relevant IDs and then search the range of chunks for those IDs.
Maintaining the search for entities itself is the same as long as you only search for the name or id.
But additionally there I implemented logic to be able to search for villager type and the offers (sells and buys). There I had already the need to differentiate how to interpret elements of the NBT tree of different minecraft versions. This might be a little effort then in future to maintain. In my eyes it would be worth it.

Your suggested approach is fine for me. I anyway will not find the time earlier to work on it. But as there is an interest in the feature I'll try to do then next year.

**Comment by EtlamGit** [comment]
Hi @cre4ture, at the moment I'm updating everything to 1.18 extended build height. Also the search was affected (solved in my development branch).

But while doing so, I noticed that some part of the search dialog seems to be outdated:
* Blocks: In the past it was reasonable to search for IDs (number) and name (string starting with minecraft:). But as "The Flattening" is quite some time ago, probably nobody will every use IDs again. Do you have an use case for the IDs that I miss at the moment?
  * I would remove the ID search box and the ID info in the first column of search results
  * I would also try to ignore a search for minecraft:air
  * Some of the block name suggestions seems to be doubled, I will try to fix that.
  * It does not make sense to put Buys/Sells for Blocks, so I will try to remove that.
* Entities: I never got the meaning of all the search boxes. Could you please explain all of them?
  * I would love to have some nice pre-filled suggestions like for Blocks
  * Name column contains the name + coordinates, coordinates have an own column. I would remove that doubled information. More useful would be the profession in case of a villager.
  * What is the use case for Buys/Sells columns? I can only get one of them to be filled with data.
