### ISSUE TITLE
Add to Wiki how to use command line

### ISSUE THREAD

**Issue by didaquis** [mrkite/minutor#205]
I saw this part of documentation and seems very interesting. Can anyone explain, or even better, document on the wiki how to use the command line. It's not clear how to use. 
The installer of minutor is setting up a "minutor" command on my terminal? 
I need open minutor app to execute a command?

https://github.com/mrkite/minutor/wiki/Command-Line

**Comment by EtlamGit** [comment]
I though everything is clear by the description in the wiki?

What operation system do you use?

I just call minutor on the command line and add the described parameters...

**Comment by EtlamGit** [comment]
You may start your tests with simple steps:
* open a command prompt, navigate to the Minutor folder, type minutor and start it from there
* add a simple parameter like -Y or -M to see direct effect

Example to export your world to a PNG image (on Windows):
```
minutor.exe --world "\\SERVER\MinecraftSaveFolder\WorldName\world" --RegionChecker --savePNG "..\myMinecraftWorld.png"
```

**Comment by didaquis** [comment]
> You may start your tests with simple steps 

This was what I needed. Thanks!
