### ISSUE TITLE
specific height by command

### ISSUE THREAD

**Issue by IronException** [mrkite/minutor#207]
Am I dumb or why cant I figure out how to set the maximum height with a command.
I want to generate images of a world from different heights but I need to know how to set the height for each png I want to save.

**Comment by EtlamGit** [comment]
Just place `-y` or `--depth` and a number from 0 to 255 on the command line.

In the [Wiki main page](https://github.com/mrkite/minutor/wiki) you can see a image that I have generated exactly the same way you ask for.

Arbitrary example:
```
minutor.exe --world "C:\Users\YourName\AppData\Roaming\.minecraft\saves\Minutor" -y 42  --exportrange -319 -64 0 255  --savePNG "Minutor_42.png"
```

**Comment by IronException** [comment]
ofc yea. thanks :)
