### ISSUE TITLE
Linux nightly builds suggestion

### ISSUE THREAD

**Issue by Kolcha** [mrkite/minutor#210]
I setup OpenSUSE build service to build Minutor for various Linux distros (including such popular as Ubuntu, Debian, Fedora, and few less common, but well-known). Few other distros can be added on request. All builds produce only x86_64 (amd64) binaries, few other architectures (like ARM or ARM64) also can be added easily.

Can [this link](https://software.opensuse.org//download.html?project=home%3Anikoneko%3Aminutor&package=minutor) be added to the ["Nightly Builds" Wiki page](https://github.com/mrkite/minutor/wiki/Nightly-Builds)?

I also updated https://github.com/mrkite/minutor/issues/165#issuecomment-570817335 to keep links up to date. Now links in that post will be permanent.

this will close #95 , #165

**Comment by EtlamGit** [comment]
We now have an own CI workflow for Minutor running on GitHub Actions.

It is also providing binaries for Ubuntu, MacOS and Windows.

**Comment by Kolcha** [comment]
GitHub Actions are good, but right now they provide just an archives with executables, and nothing more... and these executables require Qt runtime...
I think such archives are not "user-friendly" for end users

moreover, macOS archive has even not correct macOS app (in terms of fs structure) - it has just a content of app bundle instead of app bundle itself. i.e. just `Content` folder instead of `<app_name>.app` folder and `Content` folder in it.

in any case, these binaries are not easy to launch, especially for macOS. but in Windows it is pretty hard too - where will regular user get Qt runtime?

that things definitely must be improved

**Comment by mrkite** [comment]
That's why preparing binaries is always a hassle.  It takes me over 6 hours to compile a static Qt for Windows and MacOS (Linux's superior package management removes the need for static linking).

**Comment by Kolcha** [comment]
it is not necessary to build static Qt for Windows and macOS to ship app for end users... just use `windeployqt` or `macdeployqt` tool shipped with Qt SDK, it copies all required runtime stuff for your executable (it is very smart, not just "copy everything"). these tools works perfectly for single-executable apps (as yours), for apps with multiple files some tricks are required. `macdeployqt` even can produce `.dmg` file... so, there is no need in static Qt.

see my Win / macOS builds for example. they are build with dynamic Qt installed using official installer. and they are ready to use on any system. there is only one issue which Windows user may face - corresponding Microsoft Visual C++ Redistributable must be installed. but this must be done only once, and almost any user knows what it is and where to get it. moreover, nowadays in most cases it already exists on users computers. but if you worry about it, you can ship its installer too with app distribution, `windeployqt` can copy corresponding "VC Redist" installer for you.

so, again, there is no actual need in static Qt, it just bring headache for you. moreover, it is required to be very careful when using static Qt, even [some additional code may be required](https://doc.qt.io/qt-5/plugins-howto.html#static-plugins) to get essential Qt stuff (platform-specific plugins) to work correctly.

**Comment by EtlamGit** [comment]
We need HTTPS/SSL support compiled into Qt (for automatic definition file update).
This is disabled by default and it is also complicated to get into a static build of Qt.

If you find a way to do all that with the dynamically linked Qt it would be much better...

**Comment by Kolcha** [comment]
Qt is compiled with HTTPS support by default... on Windows and Linux it uses OpenSSL, on macOS - Secure Transport (built-in macOS feature).

by default, Qt is configured (during compilation) to dynamically load (like plugin) OpenSSL libraries, not linked to them. this allows app to be launched without OpenSSL libraries, but as you mentioned secure connections will not work. but it is very easy to fix it - just place 2 OpenSSL libraries near to executable.

for Windows, required OpenSSL libraries are shipped with Qt SDK since Qt 5.12.x, they can be found in `Qt\Tools\OpenSSL\Win_x64\bin` (of course, you should mark required component during Qt installation). Since Qt 5.12.x Qt on Windows uses OpenSSL 1.1.x, previous versions use obsolete OpenSSL 1.0.x. OpenSSL 1.0.x is not available for installation for previous Qt versions, so it must be compiled manually.

there is nothing to do on macOS, everything works out of the box.

on Linux - system OpenSSL libraries are used (like and Qt libraries). if you want to build own Qt for Linux, so you have 2 options: use system OpenSSL libraries or build you own. in any case then you can just copy these 2 files into your app distribution alongside Qt libraries. but this actual only if want to build "portable" app like I mentioned in previous message.

conclusion: there is nothing to do for macOS, it much more easy to use Qt 5.12.x on Windows and use shipped with it SSL libraries, use everything from distro on Linux (but building "portable" app is also possible). again, there are no reasons to build static Qt.

P.S> my app also uses HTTPS connections (at least for checking updates), and everything works fine. it is completely open source, build script are also in repo, so you can find and analyze them, and do something similar for your case. but you case is very simple: just run `macdeployqt` on macOS, and after running `windeployqt` on Windows just copy 2 OpenSSL libraries (`libcrypto-1_1-x64.dll` and `libssl-1_1-x64.dll`) alongside Qt libraries. and that's all, everything will work. again, try my builds.

**Comment by EtlamGit** [comment]
Thank you very much for that information!

Sounds if it is much easier with Qt 5.12 nowadays...
During the last years I had only self compiled Qt environments on my computer. And especially the migration to self compiled OpenSSL 1.1.x was very error prone.

**Comment by PeacePlays** [comment]
I was almost excited that someone was doing a Mac nightly build.

**Comment by EtlamGit** [comment]
Qt installed on Github for Windows seems not to contain the `Qt\Tools\OpenSSL` folder.
So we need another source for the OpenSSL DLLs. (For older Qt versions this would be always the case.)

When installing Qt myself, I also do not get the `Qt\Tools\OpenSSL` folder. Reason is that I use the offline installer, which can not install OpenSSL. You have to use the online installer.

**Comment by Kolcha** [comment]
see https://github.com/miurahr/aqtinstall/issues/155 and https://github.com/jurplel/install-qt-action#tools , this should help to get OpenSSL when running GitHub Actions

**Comment by EtlamGit** [comment]
Yes, seems to work. At least for Windows with Qt 5.12.4+ this should work.
But following the discussion in your post at aqtinstall the version number changed there from 1.1.1-1 to 1.1.1-4 during December, and now we are at 1.1.1-10. So it will be a nightmare to follow these updates. We have to update the *.yml file each time. And more difficult, we have to get notice the number has changed.
Any idea to get this easier?

**Comment by EtlamGit** [comment]
With all these stuff depending on OS and Qt version we will get a very crowded matrix build.
Maybe it is better to stop using a matrix build and have individual *.yml files for each supported OS-Qt combination?

Ideas to that topic, anyone?

**Comment by Kolcha** [comment]
I suggest to create few workflows (per OS) instead of using matrix, it is much easier to write and even more to understand when any modifications should be added in future

**Comment by Kolcha** [comment]
what about versions hell, this is "modern trend" now to hardcode exact versions... for example, look at any Python-based software, or even worst something JS-based (ugh...). almost nothing provide an option like "use latest available" or "recommended".

**Comment by Kolcha** [comment]
closing this ~2 years old issue since link is already in Wiki
