### ISSUE TITLE
Nether Update blocks and biomes

### ISSUE THREAD

**Issue by ToonSpin** [mrkite/minutor#213]
Hi, I would like to contribute blocks and biome information so Minutor will be ready for 1.16 when it comes out. Can I just submit PRs, or how does that work?

**Comment by jbmagination** [comment]
1.16-pre1 is out.

Also, look at the Minecraft forums for new items and blocks.

**Comment by EtlamGit** [comment]
@jbmagination there should be NO missing Blocks ...
It is possible to let Minecraft generate lists and worlds with all (~17000) Blocks for reference.
