### ISSUE TITLE
Minutor crashes with every version newer than 1.13

### ISSUE THREAD

**Issue by EaglesEyeEM** [mrkite/minutor#225]
Hey
I've got the problem, that even after installing your latest commit (29. April) Minutor keeps crashing when loading a world newer than Version 1.13.
Is there already a fix? I only red that some people are talking about a version 2.3.0 ?

**Comment by EtlamGit** [comment]
installing and latest commit does not fit from a perspective of wording:
You either have installed the latest release (very very old)
or you just use a self compiled version or a [nightly build](https://github.com/mrkite/minutor/wiki/Nightly-Builds)

I can verify that even the development versions for 1.16 are working.

If just "crashing" is your problem, try to create a new test world. Or provide a world download for debugging. In that case I will try to fix it.

**Comment by EaglesEyeEM** [comment]
Oh okey, never noticed these nightly builds... Thank you very much for your help!
No I have to see how to repair all the broken regions :D
