### ISSUE TITLE
Lighting mode has artifacts with 1.14 world

### ISSUE THREAD

**Issue by Kolcha** [mrkite/minutor#226]
issue appears with this commit 71b72a0b88a40455bf7e0eb4554e06a06adddd69 , old worlds (e.g. from 1.11.x) are not affected. not tested with 1.15, still use 1.14.x
<img width="989" alt="Screenshot 2020-05-09 16 44 41" src="https://user-images.githubusercontent.com/947647/81475392-911fc100-9214-11ea-9510-2c10405805c9.png">

**Comment by BigAlanM** [comment]
I just checked the latest nightly compile with world from 1.15.2,  1.14.4,  and 1.13.2.
I got the lighting artifacts with 1.15 and 1.14.    
1.13.2 works properly.

**Comment by EtlamGit** [comment]
This is a problem with the light map.
It occurred first with the crash fix and saveMemCopy.
Refreshing helps! So this is not persistent per Chunk. And therefore should not depend on stored data.


Most probably there is a timing issue with Chunk loading.
