### ISSUE TITLE
Provide export functionality

### ISSUE THREAD

**Issue by SammyIAm** [mrkite/minutor#24]
Minutor does an excellent job of rendering a top-down map, and it would be cool to be able to leverage this to automate the creation of maps.

A lot of mapper utilities exist that will generate a Google-maps style map, but these all seem to do isometric views.  A Google-maps style export would be handy, but isn't necessarily required since there are utilities that can take a single large image and reformat it for use with the Google Maps API.

**Comment by EtlamGit** [comment]
@SammyIAm please take a look at: https://github.com/mrkite/minutor/wiki/Command-Line
Is this what you expected? At least I use it to automatically generate several overview maps for the players on my server.
