### ISSUE TITLE
what file do I open to use it?

### ISSUE THREAD

**Issue by ChechenRebel** [mrkite/minutor#247]
Actually, nevermind about the nevermind.
It keeps crashing whenever I try to load ANY world.

**Comment by EtlamGit** [comment]
Try to use the latest automatic build:
https://github.com/mrkite/minutor/actions/runs/564312761

or later select one by your own from: https://github.com/mrkite/minutor/actions

**Comment by EtlamGit** [comment]
@ChechenRebel did you test with a current build?

It is known that the last official release does not work anymore.
You have to use automatic build like linked above or build yourself.
