### ISSUE TITLE
OSX builds

### ISSUE THREAD

**Issue by Macfelon** [mrkite/minutor#252]
Any idea on when OSX builds are going to resume?  Last one I see is 2019?

**Comment by EtlamGit** [comment]
Have you tried to use on of the [automatic builds](https://github.com/mrkite/minutor/actions/runs/987316362)?
(You can find them via the Action tab here on GitHub. And they always have the latest changes.)

It is not a complete OSX app (or how ever this is called there). Maybe @Kolcha can explain what to do with that *.dmg file to run or install it.

**Comment by Kolcha** [comment]
@EtlamGit, automatic builds are complete ready-to-use apps as they should be.
.dmg file is just macOS-specific disk image format, something like well-known ISO, just more "fancy". a lot of third-party apps are distributed as .dmg files, this is common practice. but .dmg inside .zip - this is very strange, and useless - .dmg already compressed and much better than zip can. but this is no big deal...

regarding the content inside that .dmg - it contains everything it should, so the app inside is ready to use. any macOS user usually knows what to do with such content :) - just drop it to /Applications folder and run :)

as far as I remember, initially, I created the script which packages the app for macOS, and this app is very simple, so there are no issues that should happen. but just to be sure I downloaded one of the archives (based on Qt 5.12) to my work MacBook (I don't have a personal MacBook anymore, sorry) and tried to launch it.

so, @Macfelon, just download the latest automatic build using the link @EtlamGit provided.

**Comment by Macfelon** [comment]
Oh!  Thanks guys, this is very helpful.

**Comment by EtlamGit** [comment]
Than we should try to get rid of the extra ZIP layer around the DMG file...

**Comment by Kolcha** [comment]
I don't think that it worth any efforts, especially when it looks like that zip layer is added by something from GitHub Actions, there is no any explicit archiving commands here.
