### ISSUE TITLE
Issues with upcoming 1.18 (extended build height)

### ISSUE THREAD

**Issue by AndrewIsOffline** [mrkite/minutor#255]
If an area is saved in a world running 21w39a or up, the area won't render properly in the viewer. The biome will show up as either unknown or ocean, and the blocks will show up as minecraft:air. This is best illustrated if the player loads in far away from world spawn:
![image](https://user-images.githubusercontent.com/6992926/136543363-af83c2c5-66dd-4617-bf8c-83c2962cf556.png)
This might have to do with the new negative y coordinates.

**Comment by EtlamGit** [comment]
Mojang did change the storage format again . . . 

* Now Biomes are not stored anymore per Chunk, put per Section. They also have a Palette that has to be decoded.
* BlockState is still stored in the same manner as before (with Palette), but the NBT keys have changed name and structure.

@AndrewIsOffline did you check, that the version number you provided is exactly the very first snapshot showing this behavior?

**Comment by EtlamGit** [comment]
The change notes for 21w39a indicate the modified Biomes, so it should be ok for the moment.

**Comment by EtlamGit** [comment]
Some intermediate status:
* I'm able to render latest snapshot again, will publish the changes soon
* more Biome data (now per Section) and more Sections will lead to about double of memory usage, so we will only be able to show half sized maps compared to now

**Comment by EtlamGit** [comment]
Everything is working for 1.18, the release is out and finally also Minecraft released 1.18 today.

@BlaCoiso: As I did extended build height implementation twice during the this year, the second time I prepared everything to render arbitrary world height. So in principle it will work with your strange dimensions. The only step missing is to detect the availability of custom dimensions.

Could you please provide some test worlds with your custom dimensions?
* I do not have the time to prepare these custom worlds.
* But I need them to figure out how to detect a custom dimension and how to detect build height for that dimension.

**Comment by BlaCoiso** [comment]
I've found an issue with the search for block feature where it ignores blocks at Y=0; about the custom dimensions, I'll look at the current format for specifying them and try to generate them again, I'll send the new world with those dimensions once I have them ready

**Comment by EtlamGit** [comment]
continue in #269
