### ISSUE TITLE
-y command line argument not working in 2.18.0

### ISSUE THREAD

**Issue by terbin** [mrkite/minutor#267]
Since 2.18.0 the command line -y switch does not seem to work anymore.
When I do **minutor.exe -y 255 -w . -s .\y=255.png** in Minutor 2.18.0 it will still create the 255.png with y-level 127.

the -y switch works fine in Minutor 2.17.0

**Comment by EtlamGit** [comment]
It will work when you change the order of parameters.

Parameters are parsed (and executed!) in order they are present on command line.
So doing "Change depth 255" and afterwards "load world" this will override the depth.
It is the same, when you first save and then load. That also does not work.

I will try to solve this anyways, as it was working before. But no guarantee it is possible. 

Reason it does not work anymore is that: we now have variable depth range based on version of world. E.g. 1.18 worlds have a different depth range than older ones. Therefore the depth slider is adapted at the moment a new dimension is detected. And we now also set a "reasonable default" depth (mainly intended for The Nether, but also for custom dimensions).

**Comment by terbin** [comment]
Thank you very much for the explanation, having to put it in a specific order is perfectly fine for me.
Couldn't find documentation on it, but might just have been bad at searching.

**Comment by EtlamGit** [comment]
I will update the Wiki to make it clearer.

A "fix" is probably not possible, as it is impossible to set specific XYZ position before a world is loaded.

**Comment by EtlamGit** [comment]
Wiki updated.
