### ISSUE TITLE
"not a valid Win32 application"

### ISSUE THREAD

**Issue by froggyt** [mrkite/minutor#27]
I use Windows XP Pro. v2002, SP3 and have only been able to run Minutor v1.6.3

Version 2.0.1, regardless of how I install it (installer or zipped minutor.exe), does not run on my system. A message box pops up with the message "C:\program files\minutor\minutor.exe is not a valid Win32 application." 

minutor.exe (v2.0.1) MD5 hash value: 87334d7d8abd6a483ed5ea2beecbc4ed

One other unidentified v2.x release previous to v2.0.1 also has the same problem.

**Comment by nerijus** [comment]
I found that:
Visual Studio 2012 Update 1 has now been released, and adds official support for running apps built with VC++ 2012 on Windows XP.
