### ISSUE TITLE
Y slider doesn't support negative y levels

### ISSUE THREAD

**Issue by reynaldo666** [mrkite/minutor#272]
The height slider on the right of the window has a range witch goes from y=0 to y=255, it doesn't support negative y levels. Please fix
![Captura de tela de 2021-12-26 18-21-35](https://user-images.githubusercontent.com/2356738/147420391-df21c381-1531-47d9-9ac0-50850ac8e629.png)
.

**Comment by EtlamGit** [comment]
Minutor 2.18.0 does support the new build height:
![grafik](https://user-images.githubusercontent.com/5821779/147456471-7b011df8-11ca-40d9-8830-2d6eb1fde80e.png)

**Comment by EtlamGit** [comment]
Have you build Minutor yourself?
What is your Operation System? (looks like Ubuntu, which version?)

The Depth Slider is adaptive to the world. So when the saved data is new the range will be extended automatically.

**Comment by EtlamGit** [comment]
Just tested on a Linux Mint machine:
* depth slider range gets adapted automatically
* negative depth is possible

**Comment by EtlamGit** [comment]
@reynaldo666 any update from your side?

**Comment by reynaldo666** [comment]
> Have you build Minutor yourself? What is your Operation System? (looks like Ubuntu, which version?)
I didn't build it myself. I got it from the [linux repository](https://software.opensuse.org//download.html?project=home%3Anikoneko%3Aminutor&package=minutor) manually. 
The OS is Ubuntu 18.04.6 LTS (bionic beaver).

> The Depth Slider is adaptive to the world. So when the saved data is new the range will be extended automatically.
My world was generated in the 1.18 snapshots, so I tried to generate another one in the 1.18 release, but it still doesn't get to the bottom of the world.

> @reynaldo666 any update from your side?
I will try the debian build, sometimes it works. Then, if it didn't work i will try to build it myself. 

Thank you.

**Comment by EtlamGit** [comment]
Hi @Kolcha, is there some manual step from the repository here on GitHub and the automatic nightly builds for Linux?

**Comment by reynaldo666** [comment]
> Hi @Kolcha, is there some manual step from the repository here on GitHub and the automatic nightly builds for Linux?
There is a linux build in the nightly builds, it's the inofficial linux repository. That's what I did. 

I've just tried to build it using qtcreator, but it didn't work. Then i realized i was using qtcreator 4.5.2, downloaded qtcreator 6.0, but I couldn't run it because the glibc that I have is the 2.27 but it needs the glibc 2.28.
I don't know what to do next.

**Comment by reynaldo666** [comment]
> Hi @Kolcha, is there some manual step from the repository here on GitHub and the automatic nightly builds for Linux?

I've just tried to build it using qtcreator, but it didn't work. Then i realized i was using qtcreator 4.5.2, downloaded qtcreator 6.0, but I couldn't run it because the glibc that I have is the 2.27 but it needs the glibc 2.28.
I don't know what to do next.

**Comment by EtlamGit** [comment]
QT Creator 6 is too new. Probably only Qt 6 support. And Qt 6 has no stable releases anymore.
I use Qt Creator 4.14.2

**Comment by EtlamGit** [comment]
I tested to download the binary from [Kolcha's nightly for Ubuntu 20.04](https://software.opensuse.org//download.html?project=home%3Anikoneko%3Aminutor&package=minutor) -> working on my Linux Mint.
My only Ubuntu test system is 16.04 and does not install at all.

**Comment by EtlamGit** [comment]
You could try to upload your world (or a fresh generated one) so I can test it here.

**Comment by reynaldo666** [comment]
> You could try to upload your world (or a fresh generated one) so I can test it here.
I couldn't upload my world (maybe its too big, 277 MB), but here is the one I created to test.
[Minutor.zip](https://github.com/mrkite/minutor/files/7785376/Minutor.zip)

**Comment by Kolcha** [comment]
First of all, there are no any manual steps to build minutor on Linux, the main thing is just using Qt 5.x (not Qt 6!). it doesn't matter which version of QtCreator is used, only Qt version is important. you can install multiple Qt versions using official Qt installer and pick any of them when importing project.
Second, builds for Ubuntu 16.04 are not available, any packages for newer systems will NOT work even they are installed (but they should not - required package dependencies versions are hardcoded during build). I'll will re-enable builds for 16.04 soon.
Third, my builds seems to be broken for ~3 days, so repositories will not contain latest packages, just slightly outdated (from last successful build). I'll fix it soon.

**Comment by EtlamGit** [comment]
Working fine under Windows and Linux Mint.
Now setting up an Ubuntu 18.04.06 . . .

**Comment by EtlamGit** [comment]
There is no urgent change in the last 3 days. New extended build height is supported for weeks.
So latest successful nightly build from Kolcha should work.

**Comment by EtlamGit** [comment]
Ubuntu 18.04.06 LTS is now running in a virtual machine:
* navigated to https://github.com/mrkite/minutor/ -> WIKI -> Nightly builds
* selected the Linux builds from Kolcha
* selected Ubuntu, manual download -> installed
* kopied reynaldos world to that machine -> open folder

=> negative depth is possible
![grafik](https://user-images.githubusercontent.com/5821779/147585973-581ff0e6-7723-47df-813f-598cbc9ac308.png)

**Comment by EtlamGit** [comment]
Maybe you can try to update definition files. Depth range is stored there.
Help-> Settings -> Definition Update -> Check now

Or delete folder `~/.local/share/seancode/Minutor`

**Comment by Kolcha** [comment]
Linux builds should be fixed, but some code changes are required, pull request was opened https://github.com/mrkite/minutor/pull/273
build server will pick changes automatically at ~3:30 AM UTC (or I can push it manually) after PR merge

**Comment by reynaldo666** [comment]
@Kolcha and @EtlamGit, 
I have good news and bad news.
Good news: I just find out I was using the wrong kit to build minutor on qtcreator (it was a path to anaconda) and I changed it to qt5.9 and I could build minutor on bionic beaver.
Bad news: I got the same problem with the height slider, it doesn't go below zero. -_-

**Comment by Kolcha** [comment]
sorry, I can't help, I don't know codebase to suggest something. only authors can help. I just the one who built packages for Linux

**Comment by EtlamGit** [comment]
Try the tip with the definition files.

And backup them before, so you can upload them here for debugging!

**Comment by reynaldo666** [comment]
> Maybe you can try to update definition files. Allowed depth range is stored there. Help-> Settings -> Definition Update -> Check now
> 
> Or delete folder `~/.local/share/seancode/Minutor` Maybe backup files found there before. Then upload them here for me to debug.

GREAT NEWS! Delete the folder worked!!! (but the update in the Settings window didn't, just for yours acknowledgment).
So it was a local bug and not a bug in minutor or maybe there's is a bug for updating the definitions.

Thank very much guys!

**Comment by reynaldo666** [comment]
> Try the tip with the definition files.
> 
> And backup them before, so you can upload them here for debugging!

I am very sorry, but I've forgot to backup.
