### ISSUE TITLE
2.18.0 not rendering some blocks at y=255 with 1.12.2 worlds 

### ISSUE THREAD

**Issue by terbin** [mrkite/minutor#280]
I have some issues with Minutor 2.18.0 not rendering blocks at y=255 in a 1.12.2 world.
Minutor 2.17.0 does not have this issue.

Here is a 1.12.2 region to reproduce (there is Obsidian at most areas of y=255)
[r.0.0-1.12.2.zip](https://github.com/mrkite/minutor/files/7920214/r.0.0-1.12.2.zip)

Map rendered with Minutor 2.17.0
![2 17 0](https://user-images.githubusercontent.com/49982226/150673927-56ff8e2b-4a52-4b8f-be27-26d0c03d636e.png)

Map rendered with Minutor 2.18.0
![2 18 0](https://user-images.githubusercontent.com/49982226/150673934-85ab3b33-4383-4d16-957d-1fc0e4dea8a0.png)

**Comment by EtlamGit** [comment]
You have a very strange world there . . .

**Comment by terbin** [comment]
Yes I do, this is the spawn of of the 2b2t.org server, but I've noticed it in other regions further away from spawn.

**Comment by EtlamGit** [comment]
Now the windows-latest build chain should work again (update at GitHub).

Here your problem seems to be fixed.
Can you build your own version (or use one from the GitHub Actions)?
There is no official release planned in the next days.

**Comment by terbin** [comment]
Thanks a lot mrkite. I do not have a build environment so I downloaded the artifacts from GitHub Actions but I get errors:
Qt5Widgets.dll, Qt5Gui.dll, Qt5Network.dll and Qt5Concurrent.dll are missing.

Can I just download qt from here "Installer 4.2.0"? https://www.qt.io/download-open-source

**Comment by terbin** [comment]
Used the nightly build from here https://github-wiki-see.page/m/mrkite/minutor/wiki/Nightly-Builds

Works fine! Thank you for the swift fix.
