### ISSUE TITLE
Allow render coordinates to be out of bound of existing terrain.

### ISSUE THREAD

**Issue by MajsterTynek** [mrkite/minutor#289]
I want to map out areas in a known boundary that has a specific shape.
I don't like that when renders constantly change their size as this makes comparisons difficult.

Additional suggestions:
- Option/parameter for expanding render to region size (in 512x512 tiles)
- Option/parameter support for coordinates like in `*.mca` file names.
- Option/parameter for rendering each region into a separate tile. 
(should it allow different sizes?)

**Comment by EtlamGit** [comment]
If I understand your suggestions correctly, it is already supported. Maybe not the way you like, but possible.
Have you checked: https://github.com/mrkite/minutor/wiki/Command-Line
* You can export "any" bounds you want. (Yes, it is limited to Chunk boundaries.)
* You are free to use any filename you like. Different names will result in multiple files.

But to get what you want you may have to wrap several calls to Minutor in a script file. This script can loop over the regions you want, calculate the bounds and call `Minutor --save xyz.png`. I'm doing that for my worlds.

**Comment by MajsterTynek** [comment]
I have mixed up everything, but still, I meant for both console and GUI versions of Minutor. 
I mostly meant the GUI as it gets stuck when using arrows and cannot type in more or gets reverted to min/max.
Like a button/switch for expanding coordinates to full region tiles, when render occurs (without changing inputs?)

Also, I don't like calculating region boundaries manually, thus asking for support of this kind.
For example, if we input 1,2 - 4,5, it will multiply internally by 512, and add 511 to the right-bottom one.

Well, I do use scripts myself, but starting it up every time for 40k+ times takes time and system resources.
If Minutor supported the export of regions tiles, it would ease work for others, including myself. 
(+updating only if modified? checking timestamps? compare existing png with mca?)

Personally, I am _thinkering_ on GUI for wdl previews, so I could compare world snapshots.
I am sorry I am overthinking everything. ¯\\\_(ツ)\_/¯

**Comment by madmaxoft** [comment]
I assume that you want to update the rendered tiles when the underlying region file changes, which to me sound more like a scriptable task - "compare file timestamps, if newer, use Minutor to update the tile". For this, you do really need to start multiple instances or Minutor needs to implement some form of commandline batch processing, but I'd venture a guess that starting multiple instances at that point doesn't hurt performance that bad, since the executable is already cached by the OS wherever possible.

**Comment by EtlamGit** [comment]
I added some of your ideas to a [new branch](https://github.com/EtlamGit/minutor/tree/snap-png-export-to-chunk-or-region)
* export GUI allows now values to the next Region boundary
* there is a selection option to snap to Chunks (like before) or Regions (your wish)
* this selection is stored in the settings and preserves its state

Some testing is still necessary, especially corner cases.

**Comment by EtlamGit** [comment]
@MajsterTynek is the added functionality solving what you expected with this Issue?
Then we could close it.

The missing topics (defining names for tiles, restrict to only changed tiles, ...) is stuff that can easily be done via external scripting. I think it is not the right approach to add "scripting support" into a GUI application.
But if you describe some more scenarios in detail, we can change the command line interface or add some more stuff that helps there.

**Comment by MajsterTynek** [comment]
I forgor 💀

**Comment by EtlamGit** [comment]
Just post anything related here, I will get noticed even on closed Issues.
Or create new Issues when you find something new.
