### ISSUE TITLE
[1.18.2] Biome number limit

### ISSUE THREAD

**Issue by drakray** [mrkite/minutor#325]
There seems to be a limit at 255 biomes, which mean adding definition for BoP, BYG and Terralith is not working(304 biomes total)

**Comment by EtlamGit** [comment]
Vanilla Minecraft has ~70 Biomes.
Do you use all that 304 Biomes at the same time (in the same world)? Does that work in Minecraft itself?

The reason for this limit is to save some RAM resources. But as it is <1% of total memory usage, we may consider to change that when the use case is reasonable.

**Comment by drakray** [comment]
Yes it does, yes I do :P
I have even more registered biome than that, with TwilightForest and Undergarden, and now BeyondEarth
I don't think there is a limit for the number of biome registrable, since the is no longer numeric value for them(but not sure about that)

**Comment by EtlamGit** [comment]
There is always a "limit" as some integer data type is needed for internal processing.

But as you confirmed the use case, I will extend the data type in Minutor to 16bit (65536 Biomes)

**Comment by drakray** [comment]
I think it will be enough, I don't think there is that mush biome in every existing mods (though never say never XD)

**Comment by drakray** [comment]
Quick question, will there be a Release for this soon, I don't think I can compile this by myself -_-'

Thank you for your good work, best map viewer for years :D

**Comment by EtlamGit** [comment]
It is possible to use the automatic build which is done for each commit. You can find them via the [Actions] tab.

But as I missed to update the version number, there might be an 2.19.2 soon.
