### ISSUE TITLE
multiplayer version

### ISSUE THREAD

**Issue by killerkong24** [mrkite/minutor#334]
do you think it would be possible to make a multiplayer version of this or can you only get single player world data

**Comment by EtlamGit** [comment]
It depends where your multiplayer world is hosted.
* For my self hosted worlds, I have network access to the world storage folder. There Minutor works exactly like for single player. You can see everything when it is stored. So it is not live or real time, as Minecraft has to store the data to disk before Minutor can read it.
* For rented server madmaxsoft described, that the data is not accessible. What I do in this case is to regularly download a backup of the server. You could even setup a script for that doing the backup e.g. every hour. On that local copy Minutor works exactly like for single player. To easy startup, I use a batch script to start Minutor with that backup folder.
