### ISSUE TITLE
Map/World Location

### ISSUE THREAD

**Issue by power1jj** [mrkite/minutor#340]
There is one guy in every group. apparently, that's me. I've looked everywhere for a tutorial on finding my map. I have windows 10 version and I don't have a Roaming/.minecraft folder. I can find information at: ...AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\... using some help from online, but that doesn't seem to work. I've tried to do my diligence to check everywhere on this, but I can't find anything. Any help is appreciated.

**Comment by power1jj** [comment]
![image](https://user-images.githubusercontent.com/59424575/196291290-8d5e844d-412f-4cbc-996d-6e48d0db157c.png)

**Comment by JDHnz** [comment]
You are using the Bedrock edition, but Minutor works with the Java edition

**Comment by power1jj** [comment]
Thank you!

**Comment by JDHnz** [comment]
@power1jj check out https://minecraft.fandom.com/wiki/Tutorials/Programs_and_editors/Mapping#Map_viewers for some alternatives that support Bedrock
