### ISSUE TITLE
water color End dimension since 2.18.0

### ISSUE THREAD

**Issue by terbin** [mrkite/minutor#345]
Since minutor 2.18.0 water in The End is rendered as gray.
In minutor 2.17.0 water in The End was rendered with a blue color.

1.12.2 example region file:
[r.-103.60.zip](https://github.com/mrkite/minutor/files/9974117/r.-103.60.zip)

region file rendered with minutor 2.17.0
![2 17 0](https://user-images.githubusercontent.com/49982226/200912886-ea25213e-bf71-4426-87e1-e06f9e9c3a6f.png)

region file rendered with minutor 2.18.0
![2 18 0](https://user-images.githubusercontent.com/49982226/200912925-f0491097-a0c8-4497-a608-98149a3bdbc5.png)

water is also rendered grey in 2.19.1.

Is this intentional or a bug?

**Comment by EtlamGit** [comment]
Water should be blue.
The same way like in Minecraft, so brownish in Swamps and cyan in warm ocean and normal blue in The End.

I just tested to create a new End and placed some water there -> looks blue

Could you:
* delete/update definition files
* or check version of definition files (vanilla_biomes->1.19.2 / vanilla_blocks-> 1.19.22w13a)
* provide world download

**Comment by EtlamGit** [comment]
![grafik](https://user-images.githubusercontent.com/5821779/200918534-6b7fdc99-aadf-403c-b342-81a2f1522040.png) (2.19.1)

**Comment by terbin** [comment]
I will update the world.
You are correct in assuming it was generated prior to 1.13. it has never seen a newer version.

I will upgrade it to 1.19.2 and send you the world download.

**Comment by EtlamGit** [comment]
No world download necessary.
The old storage format should be explanation enough.

**Comment by EtlamGit** [comment]
@terbin you just have to update the definition files to get your water blue again. (or wait 1 week for auto update)
