### ISSUE TITLE
pre 1.13 blocks over water rendering issue

### ISSUE THREAD

**Issue by terbin** [mrkite/minutor#347]
There is an issue rendering blocks directly over the water in pre-1.13 regions perhaps.

There is a layer of snow at y=63 directly over the water. 

Here is the example 1.12.2 region
[r.-74.-93.zip](https://github.com/mrkite/minutor/files/9995284/r.-74.-93.zip)

Rendering the 1.12.2 region with latest minutor - rendering incorrectly. 4 Chunks not rendering snow at y=64
![map](https://user-images.githubusercontent.com/49982226/201481903-ed0ee003-d749-4d3f-83ab-8d5102964ea7.png)

Updating the region to 1.19.2 and rendering it with latest minutor - rendering correctly
![map](https://user-images.githubusercontent.com/49982226/201481931-47c24a85-b480-4438-95d4-5b77f1b0a679.png)

**Comment by EtlamGit** [comment]
When I open this Region file in NBTexplorer and look to these Chunks
(e.g. -2349/-2945 versus -2349/-2946)
* (I see that there is a Section Y==14 with some glass)
* Sections 0 to 4 are present which is expected, as 16 Block layers per Sections is 0..3 for 0..63 and another one for 64
* Section Y==4 contains Block data field and Data data filed with all 0 -> AIR

So it would be expected, that there is NOTHING at Y==64

When I open this Region in Minecraft 1.12.2 I can see your snow Blocks . . .
So you are right, the snow is present, but not stored on disk and therefore not rendered.

I have no clue, why this layer is not stored!

**Comment by EtlamGit** [comment]
What is interesting is, that it works in Chunks that are located more to the north.
It seems, that only these Chunks are affected that have the glass layer at Y==239

**Comment by terbin** [comment]
Good point
here's a bigger section - one more region to the south. It's pretty strange


1.12.2 region file
![map](https://user-images.githubusercontent.com/49982226/201493512-d5ff9ef5-1dd4-424f-9d4e-f4abc34033b9.png)

updated to 1.19
![map1](https://user-images.githubusercontent.com/49982226/201493520-72cac2e6-7c4b-4a5c-aa08-e440b23fbcf8.png)

**Comment by EtlamGit** [comment]
Your build looks nice, Christmas themed?
Maybe you could add that Region file also? Than I have something to show for the kids ...

**Comment by terbin** [comment]
Hi Etlam,

Absolutely - here is the world download with level.dat
[Emperium Christmas Base 2019-12-25.zip](https://github.com/mrkite/minutor/files/9996624/Emperium.Christmas.Base.2019-12-25.zip)

It's from an anarchy server called 2b2t, so while I've removed some signs, better doublecheck before you show the kids.
I run a mc museum server for destroyed builds from that server: thearchive.world

Something your kids might enjoy are my cinematics from that server: https://youtube.com/terbin
