### ISSUE TITLE
Is it possible to find item hotspots?

### ISSUE THREAD

**Issue by LaserKaspar** [mrkite/minutor#353]
I am running a modded minecraft-server and somewhere in the world are thousands of items. I would like to locate them quickly. Is this possible?
Really appreciate this project!

**Comment by EtlamGit** [comment]
What I would do (modded or not nodded should not matter in this case):
* download a server backup
* open that with Minutor
* press CTRL+I (or menu Overlay->Items)
* scroll around the map near the location you expect the items to be
* zoom out may help

I don't know if that is fast enough for you, as you have to locate the items manually (by scrolling the map).


Option 2 is to search for items:
* (open the map from 1)
* Open menu Search->Search for Entity
* enter "item" as entity type, select exact search and use a large Radius for search

That fins mostly eggs in my case, so also maybe not exactly what you want.
But it is possible to export the search results and process them externally.

**Comment by EtlamGit** [comment]
@LaserKaspar does my answer help? Or at least goes in the right direction?
When not, please describe your problem in more detail.

**Comment by LaserKaspar** [comment]
It is not possible to find many items if they are at the same location. So your suggested method sadly does not work.

If for example, a chicken farm laid 10k eggs on a single block, I want a way to locate that block quickly. Something like a heatmap for items, if that makes sense? Visually It is very difficult to tell if there are two items on a given spot or 10, or even 100.

**Comment by EtlamGit** [comment]
When you hover the mouse over these items -> you get the amount of items in the status bar:
![grafik](https://user-images.githubusercontent.com/5821779/211210930-04c0fc07-1303-44e5-be26-c9bd07992ef5.png)

Yes, that is not automatic and not a heatmap.

When you take the second suggestion (search for "item"), you can export all items and then filter them externally. Your external filter tool could report items at same position above a threshold.

Yes, you have to develop that filter tool. But it should be possible with 10 lines of Python.
(use hashmap with position as key and count up the value, then print all keys for large value).

**Comment by EtlamGit** [comment]
@LaserKaspar did you find time to test the mouse over information? Or to process exported item data?

Is there something else we could help here?
