### ISSUE TITLE
Dark Prismarine slab shows as water even if it's not waterlogged

### ISSUE THREAD

**Issue by Delvin4519** [mrkite/minutor#361]
A build with dark prismarine blocks and slabs shows as water in minutor even if there's no water visible or waterlog at the surface. Minutor seems to be rendering dark prismarine slabs as water for some unknown reason

![image](https://github.com/mrkite/minutor/assets/23464599/2a2fa4d1-4e95-4536-82d0-9bf81bc82cba)

![image](https://github.com/mrkite/minutor/assets/23464599/ff1399f2-5e71-40f6-add9-85abfc0e702a)

**Comment by EtlamGit** [comment]
when looking into the Block definition file:
* prismarine_lab should be `#699f8a`
* dark_prismarine_lab should be `#3f5ce4`

so this is obviously wrong . . .

**Comment by EtlamGit** [comment]
`#36604f` would be the right color

**Comment by EtlamGit** [comment]
@Delvin4519 please force an definition update and report if it is fixed now.

**Comment by Delvin4519** [comment]
I can't seem to find a way to force a definition update. I've tried the settings option and clicking check for definition update, and reinstalling minutor and again trying to force a definition update, but it still shows a block definition of 1.20 23w12a.

**Comment by JDHnz** [comment]
@Delvin4519 The definitions are downloaded to %appdata%\Local\seancode\Minutor (on the Windows version, at least). That folder can safely be deleted and Minutor will download a new version of the definitions the next time it starts up.

**Comment by Delvin4519** [comment]
I've done that now resetting/deleting the definitions folder location, and minutor is still re-downloading the old definitions file from 1.20 23w12a. So the fix doesn't show up yet.

**Comment by JDHnz** [comment]
Looking at the [definitions](https://github.com/mrkite/minutor/blob/master/definitions/vanilla_blocks.json) source file, we can see that it is tagged with the version of 1.20.23w12a, which corresponds to the last Minecraft version where new blocks were added, so what you are seeing is likely correct. Have you tried opening the world file in your original message to see if the colours have been updated?

**Comment by EtlamGit** [comment]
Yes, my fault. I forgot to increment the version number.

**Comment by EtlamGit** [comment]
Should work now.

You can always download the latest definition and overwrite the local file in %appdata%\Local\seancode\Minutor with it.

**Comment by Delvin4519** [comment]
Seems though the hex code for the fixed file is incorrect, since there are 7 characters for the hex code so it results in an invalid color.

![image](https://github.com/mrkite/minutor/assets/23464599/6241ed1a-17a9-4994-8356-c7380b6e8a51)

**Comment by EtlamGit** [comment]
Too fast changes increase the chance for errors ... next one is checked in.

**Comment by Delvin4519** [comment]
Closing this issue as resolved
