### ISSUE TITLE
Search limits

### ISSUE THREAD

**Issue by thewho333** [mrkite/minutor#362]
### Versions
- Minecraft 1.19.2
- Minutor 2.19.1

### Problem 
- Searching for block name seems to be limited to 16001 results.

### Sulution
 - I assume it's performance related? Maybe add a setting for max number of results?

**Comment by EtlamGit** [comment]
Yes, the limit is to keep memory usage and performance under control.

What is your use case, that you need more results?
You are definitely not able to look individually at each of these results.
There is a Block Statistics dialog, that has no limit.

**Comment by thewho333** [comment]
Thank you 👍 Block statistics is exactly what I needed.
I assumed that 2.20.0 was only for MC 1.20 worlds

I'm configuring an ore generation mod and need to know the amount of an ore being generated.

**Comment by EtlamGit** [comment]
@thewho333 can we close this?

**Comment by thewho333** [comment]
Sorry. Didn't know I could do that 😅
