### ISSUE TITLE
Search for blocks added by mods

### ISSUE THREAD

**Issue by thewho333** [mrkite/minutor#363]
### Versions
- Minecraft 1.19.2
- Minutor 2.19.1

### Problem 
- Searching for block names added by mods makes the "Search" button change to "cancel" but nothing happens and pressing "cancel" does nothing.

### Sulution
 - Allow searching of non-minecraft blocks.

**Comment by EtlamGit** [comment]
I will look into the button behavior.

To be able to search for modded Blocks (or do anything else with them), you have to add a definition file for that mod.
Only Blocks in a definition file are known to Minutor, all others are just "unkown".

**Comment by EtlamGit** [comment]
You have to create a definition file matching your mod.
It is just a JSON file with all of your Blocks and has to be added in Minutor.

Explanation is [here](https://github.com/mrkite/minutor/blob/master/definitions/readme.md)

**Comment by EtlamGit** [comment]
You should take `vanilla_blocks.json` as example and create a `yourmod_blocks.json` from that.
