### ISSUE TITLE
Grass Rendering Pink or Missing

### ISSUE THREAD

**Issue by KissTheCook2004** [mrkite/minutor#376]
minecraft:short_grass is rendering as pink, no matter the height or biome
minecraft:tall_grass and other biome-specific colored blocks are rendering normally
World version 1.20.4, vanilla

![image_2024-08-12_132648586](https://github.com/user-attachments/assets/0bd82c12-6620-47eb-b210-d4c1f64a777f)
![image](https://github.com/user-attachments/assets/eab24d46-69ce-455b-b1ac-13112147f8d6)

**Comment by EtlamGit** [comment]
Do you use latest release version of Minutor?
Did you try to update your definition files?

It should look like this:
![grafik](https://github.com/user-attachments/assets/170e77e3-f25d-492d-a511-2805507a3093)

**Comment by KissTheCook2004** [comment]
Latest version yes, outdated definitions, despite a fresh install

Updated them manually and worked fine

**Comment by EtlamGit** [comment]
They should update automatically every 7 days.
You can force that in "Settings".
