### ISSUE TITLE
mapview.h:32:29: fatal error: QtWidgets/QWidget: No such file or directory

### ISSUE THREAD

**Issue by foulowl** [mrkite/minutor#43]
Trying to build I get:
```
In file included from mapview.cpp:29:0:
mapview.h:32:29: fatal error: QtWidgets/QWidget: No such file or directory
 #include <QtWidgets/QWidget>
```
But looks like I have that file:
```
locate QtWidgets/QWidget
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidget
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidgetAction
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidgetData
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidgetItem
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidgetItemV2
```
This is both with the source tarball and git rev 851bbbc72b556d1177789250e141f9666ed38cca.

Thanks!

**Comment by michalsrb** [comment]
I've got the same error. The problem was that I was using qmake for Qt4 which doesn't set up Qt5 include paths. With qmake for Qt5 (command `qmake-qt5` in OpenSUSE) it works. Hope it helps anybody with similar issue.

**Comment by mrkite** [comment]
Just to note that you can also do `qmake -qt=qt5`  to force qmake to use the qt5 version for those people with multiple Qt installs.
