### ISSUE TITLE
Possible feature addition: Biome display

### ISSUE THREAD

**Issue by erich666** [mrkite/minutor#46]
I see that Minutor has been trimming back on viewing modes since a few years back, but has added biome and block ID display. You might be interested in the recent addition to Mineways, adding biome display as a viewing mode. See the image attached. The current Mineways code does not support reading in the grass and foliage PNGs, the default biome colors are just hard-wired in - that's plenty for most people.

The hard part of adding biome display to Mineways was figuring out all the equations used for computing the color. Most of that code is now encapsulated in biomes.cpp and .h in https://github.com/erich666/Mineways/tree/master/Win; there's a bit in MinewaysMap.cpp, mostly in checkSpecialBlockColor() at the end. The only bit that Mineways could not emulate was Swamplands, a biome which varies between two very different colors based on a location fed into a Perlin noise function.

Anyway, just a suggestion, and I'm happy to explain any of my code. I'm also happy to have gotten a huge leg-up by basing Mineways off of Minutor. I hadn't looked at Minutor in awhile - wow, your block read speed has improved enormously since a few years back, I'll definitely have to take a look at it.

**Comment by highthunder** [comment]
If anyone is still interested in this, I also wanted this feature, so I added biome display to my local build of Minutor.  Just to clarify, by biome display I mean a toggleable view mode in which all blocks in a given biome type have the same color.

I got around the need to compute the colors by adding colors to the biome.json definition file, which of course allows for easily adding moded biomes.

I still need to finish defining colors for all of the biomes before it will be ready for a pull request, but would there be interest once I finish?

**Comment by erich666** [comment]
> I still need to finish defining colors for all of the biomes before it will be ready for a pull request

This is all in a table for you already.

I hope you did look at Mineways' display system ([try it out](http://mineways.com), and [source is here](https://github.com/erich666/Mineways)), and I definitely hoped you used the data in [biomes.cpp](https://github.com/erich666/Mineways/blob/master/Win/biomes.cpp), which has all the temperature and rainfall data, as well as the special odd changes for swamp, roofed forest, mesa, etc. I spent _way_ too much time gathering all these weirdnesses, no reason to go through that again.

Anyway, I hope someone else has an interest - I think it's kind of cool to be able to turn on the biomes in Mineways.

**Comment by highthunder** [comment]
I made a quick attempt to run Mineways to see how it looks, but sadly I ran into some issues with Wine _what a surprise :/_

But from looking at biomes.cpp that you linked it looks like you are talking about the subtle differences in grass color as they actually appear in Minecraft (which might also be interesting to add to Minutor).  

But what I have written is more for visualization, like the 'Mob Spawning' option, so oceans and rivers are blue, forests are green, mesa might be orange, etc. My main intention was to be able to easily search for various biomes, especially rare ones.

To show what I'm going for, here's some screenshots with and without my biomes colors toggled (and my very rough and incomplete color definitions).

![biomes](https://cloud.githubusercontent.com/assets/5083761/19424425/27f02234-93f7-11e6-82ea-9b54b7f17087.png)
![normal](https://cloud.githubusercontent.com/assets/5083761/19424426/27f03788-93f7-11e6-8d6d-c97e3947d9aa.png)

**Comment by madmaxoft** [comment]
I don't think this feature is suited for Minutor. Have you tried Amidst? It is a tool specifically designed to display biomes and structures, with zoomable display (zooming out even into <100% zoom, which Minutor won't do)
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/2626547-amidst-now-has-1-9-support-and-a-new-home

**Comment by erich666** [comment]
Just for comparison, here's Mineways' biome mode off and on. It's actually surprising to me how much Minecraft changes the color of stuff in some of the biomes.

![biomes_off](https://cloud.githubusercontent.com/assets/803995/19440792/33115a16-9451-11e6-9ad7-c5ea42d38f8d.jpg)
![biomes_on](https://cloud.githubusercontent.com/assets/803995/19440791/330dd5c6-9451-11e6-9930-dfb18965a41e.jpg)

**Comment by EtlamGit** [comment]
@highthunder if you have trouble to find good colors, use the ones from AMIDST as linked by madmaxoft. Most Minecrafters would be familiar with them.

Do you use AMIDST? As madmaxoft states, it has the feature you are looking for. And erich666 was describing a different feature, as you can see from his images.

But in my opinion it would also be possible to add this to Minutor. Extending *_biomes.json with the colors should be easy and the data is present already.

(Regarding the feature from this issue: It is still on my list of things to add. But at the moment I lack spare time...)

**Comment by highthunder** [comment]
My feature would handle some things that AMIDST doesn't: biomes edited by McEdit or similar tools or terrain generated in different versions. As well as the ability to quickly switch back and forth between these views.  AMIDST is great for predicting where biomes and structures will be, while Minutor is great for seeing what is actually in a world.

Aside for populating biomes.json (and thanks for the suggestion to borrow the colors from AMIDST) the feature I'm talking about is done, I was just checking to see if there was any interest for me to share it.

**Comment by highthunder** [comment]
Are you interested in adding my feature to Minutor?  If so, should I create a new issue for it, issue a pull request, or something else?

**Comment by mrkite** [comment]
Sure, issue a pull request.

**Comment by EtlamGit** [comment]
@highthunder I have reviewed your feature and would like to ask a question:
Do you intend the Biome overlay to be a:
1. completely different rendering mode
2. transparent overlay above the already rendered chunks

I'm asking, because rendering gets slow due to all the added features over the last years. If you say (1), we could write a separate and fast render function only for Biome display and keep it out of the normal rendering. Maybe there is also other stuff that can be optimized.

**Comment by EtlamGit** [comment]
Hello @erich666 !
As you probably assumed from my commit to your project, I try do add this Biome color feature during Xmas. I browsed the Minecraft code with MCP931 (1.10) and noticed some places which differ from Minecraft-Wiki and your code. Maybe you have time to give some comments about that...

* It seems that the limit below Y=64 is not valid anymore. At least I found no check for negative values. It looks like the temperature increases the same way as it decreases above.
* The factor is exactly 1/600 per meter.
* There is also a perlin noise generator on the normal temperature deviation. Not only in Swamps. But probably I will skip this for performance reasons.
* Birch and Pine do not use Foliage.
* Changed temperature and humidity values are already pushed to Mineways.

All the other stuff looks consistent for me.

Merry Christmas and a happy new year
EtlamGit

**Comment by EtlamGit** [comment]
And another question for @erich666 : 
Do you know how (or where) the Foliage/Grass color is applied to Blocks like Reeds or TallGrass?
I assume, that their texture is mixed in some way with this color. But up to now, I did not found how this is done. Just simple mixing would result in too dark colors. So there must a trick to get it brighter.

**Comment by erich666** [comment]
Sorry, I can't answer most of your questions because I don't recall - about all my knowledge is encoded in my Mineways code. Study it and you'll see what I do, though of course it may well be wrong or may have changed.

> Birch and Pine do not use Foliage

It's Birch and Spruce, and the hard-wired color values are covered [here](https://github.com/erich666/Mineways/blob/master/Win/MinewaysMap.cpp#L1053) in the Mineways code.

> Do you know how (or where) the Foliage/Grass color is applied to Blocks like Reeds or TallGrass?

I don't recall anything special I did for tall grass, it's considered a grass in [the code](https://github.com/erich666/Mineways/blob/master/Win/MinewaysMap.cpp#L1103), which gets changed as usual [here](https://github.com/erich666/Mineways/blob/master/Win/MinewaysMap.cpp#L1312). So, it's just another form of grass, and I assume you take the gray and multiply by the color computed by [BiomeColor](https://github.com/erich666/Mineways/blob/master/Win/biomes.cpp#L315), as usual.

I don't have sugar cane getting affected by the biome, and in fact it comes in colored (tallgrass.png is gray), so I'm pretty sure that's right.

Anyway, if you do confirm any changes, please let me know. I'm ridiculously busy until August, but it'd be fun to delve back into this area after then.

**Comment by EtlamGit** [comment]
When applying the colors retrieved from the Biome Colorizer, they should be mixed somehow with the "texture" of the corresponding block. Minecraft is doing this probably on the GPU, at least OpenGL is doing this for free.
Not doing it (pure Biome Colorizer) looks like this:
![minutor_gf_direct](https://cloud.githubusercontent.com/assets/5821779/21504041/ffe62926-cc5b-11e6-8f85-5378e4e53f91.png)
Averaging texture and colorizer:
![minutor_gf_averaged](https://cloud.githubusercontent.com/assets/5821779/21504039/fe83091e-cc5b-11e6-9da5-c85460b1dabf.png)
Multiplying texture and colorizer:
![minutor_gf_multiplied](https://cloud.githubusercontent.com/assets/5821779/21504040/fe8783d6-cc5b-11e6-94f9-13e3a0eb758e.png)

I have to play a bit to view the vanilla color behavior...
But the trees are not so visible anymore, maybe we should give them a bit more contrast.

**Comment by EtlamGit** [comment]
And yes, Sugar Cane (reeds internal to the game) is changing by the Biome.
The same is with Vines, Fern, double tall Fern TallGrass and double tall TallGrass.

Also the Jungle Leaves texture has some yellowish parts.
Birch ans spruce/pine is completely colored and extra handled by the game code.

**Comment by EtlamGit** [comment]
Just to save my impressions from vanilla Minecraft:

Some trees close to spawn, Birch is different and Leaves darker than Grass:
![2016-12-27_18 24 58](https://cloud.githubusercontent.com/assets/5821779/21504845/86733334-cc62-11e6-8991-58b222eb6809.png)

The Swamp in the South, with clearly visible perlin noise generator (we only have the brownish color):
![2016-12-27_18 21 21](https://cloud.githubusercontent.com/assets/5821779/21504859/9f8c9284-cc62-11e6-8ae2-931ade004391.png)

And an acacia tree in the middle of the map which has 2 Biomes:
![2016-12-27_18 22 58](https://cloud.githubusercontent.com/assets/5821779/21504878/bf1ffae6-cc62-11e6-805e-40ecca17b9c9.png)

**Comment by EtlamGit** [comment]
I found a nice looking way to mix the hue (color tone) and average saturation and lightness.
Now also the foliage is finished (and trees are darker than the grass).
Any comments before I create a PullRequest?
![minutor_final](https://cloud.githubusercontent.com/assets/5821779/21547784/83b6ca2a-cde8-11e6-87a3-2d579c4f8e8e.png)

**Comment by mrkite** [comment]
Looks good.  Go for it.

**Comment by madmaxoft** [comment]
Is it still possible to turn the biome-dependent colors on and off? I wouldn't like to lose the current display style.

**Comment by EtlamGit** [comment]
Easy toggling the mode from the current one described here and the "old" one is not possible for several reasons:
* The old mode used too bright colors for trees. This is adapted to vanilla Minecraft now and is obviously different. So some colors have changed.
* The Biome based mode uses the "colorized" color and mixes it with the averaged vanilla texture. But vanilla textures for grass and leaves are monochrome (in most cases) . So you would get gray trees and grass.

What you can do instead is this: Save (or maintain) the old definition files. If Minutor loads the old files, it behaves exactly as before. Every new feature is only enabled when triggered through the definition files.

What could be implemented is: Switch off Biome based interpolation via temperature and humidity. This could easily be done be forcing temperature and humidity to 0.5. Then you get something very similar to the old mode (but with darker leaves). You can also force this yourself by removing every temperature and humidity tags from `vanilla_biomes.json`.
