### ISSUE TITLE
Feature Request: Batch mode to export Maps as png

### ISSUE THREAD

**Issue by DC-ObeY** [mrkite/minutor#50]
It would be nice if minutor would support a batch mode like
PATH-TO-Minutor\Minutor.exe "Path to Map" "Path to Export File\export.png"

so i could automatically export the explored map and upload it to my webspace :-)

best regards

**Comment by EtlamGit** [comment]
Everything is implemented and published in release 2.1
@DC-ObeY please take a look here: https://github.com/mrkite/minutor/wiki/Command-Line
