### ISSUE TITLE
Show current layer only

### ISSUE THREAD

**Issue by foulowl** [mrkite/minutor#6]
I would like the feature to show _only_ the current layer, nothing above or below it.  For example, this would be useful if I've built a structure and would like to inspect it layer by layer to see if I've made rooms the right sizes, without having the floor layer be in the background.

The background color would then have to be user-selectable, eg, set a blue background when working on a building made out of stone bricks, etc.

**Comment by IronException** [comment]
I dont see the need for a user-selectable background. Ofc this would be very useful also for normal cases. For an easy implementation it could be just black, like it is when there is no block at all and there is void

**Comment by EtlamGit** [comment]
merged already some time ago
