### ISSUE TITLE
Dependancy on libqt5core5

### ISSUE THREAD

**Issue by Lantizia** [mrkite/minutor#61]
Hi,

When installing in Ubuntu 14.04 I've noticed it won't install as libqt5core5 no longer exists, it is now libqt5core5a.  It seems libqt5core5a doesn't 'provide' libqt5core5 either and according to some sources I've read it seems to be intentionally renamed to cause this issue.

Anyway the issue could be fixed by having your debian control file depend on either like thus...

Depends: libqt5core5 (>= 5.0.1+dfsg) | libqt5core5a (>= 5.2.1+dfsg)

Thanks :)

**Comment by nigels-com** [comment]
Yeah, came across the same issue.

**Comment by amgraham** [comment]
Is there any word on this? I'm still having the same issue.

**Comment by EtlamGit** [comment]
We dropped support for Ubuntu 14.04.

Sorry.
