### ISSUE TITLE
Unstable on Nvidia 980 TI with 4k display in Windows 7 64 bit

### ISSUE THREAD

**Issue by siggjen** [mrkite/minutor#70]
When opening a map on Windows 7 64 bit it works well with small windows. When I try to use too big window or maximized it becomes unstable. My display resolution is 2x4k, hardware: 32 GB RAM, Intel i7 4790K, Nvidia 980TI.
Unstable as in the map becomes black/white squares and map is shown as trail from mouse cursor, and sometimes more portions are shown, but it changes all the time. If I make the window smaller it works as before I got the 980TI with 4K screens.

**Comment by EtlamGit** [comment]
Which version of Minutor do you use?
This problem should be fixed by all the commits I have done for 64bit support and automatic chunk cache size calculation. I also use bigger monitors.
But the last official release (2.0.1) is still only 32bit and therefore does not work on monitors larger than HD. Maybe you have to compile the current source to get 64bit support (and much more).

**Comment by madmaxoft** [comment]
I'm seeing similar behavior even with a smaller screen and much lower memory usage (around 500 MiB), it seems to start happening as soon as the OS runs out of physical RAM. I'm running on 64-bit Win7, I have swap set to OS-managed, so it should still be able to alloc more memory / swap out unused programs.

I'm beginning to think that chunk sparsing (splitting each chunk into 16 vertical segments and not storing all-air ones) would be beneficial even for Minutor.

**Comment by siggjen** [comment]
I am using release version of Minutor as I don't have any build system and no intention to set up for compiling Windows binaries.
Maybe it's possible to get a new release or at least a binary with 64 bit support and newer features?

**Comment by mrkite** [comment]
Yes.. It's definitely way past time to release an update.   For Windows  I need to rebuild a static library version of Qt5.5 first though, and I've been putting it off because it's so time consuming.  Plus I'd like to upgrade my dev machine to Win10 and make sure nothing breaks horribly.

**Comment by EtlamGit** [comment]
> I'm beginning to think that chunk sparsing (splitting each chunk into 16 vertical segments and not storing all-air ones) would be beneficial even for Minutor.

Chunk segments with only air are not stored (already now). 64bit Windows is getting normal and with >4GByte of RAM it works even on larger monitors. So this problem will vanish in the near future...

**Comment by EtlamGit** [comment]
> Yes.. It's definitely way past time to release an update.
@mrkite : is there something I can help in preparation for a current release?
