### ISSUE TITLE
Dark oak fence is "unknown".

### ISSUE THREAD

**Issue by Fabian42** [mrkite/minutor#76]
Where there should be a dark oak fence, there is a pink pixel and the decription says "unkown" and of course the biome name and coordinates. The ID is 191, should be correct.

**Comment by EtlamGit** [comment]
Have you tried the latest version, here from GitHub?
(not the latest official release, but self compiled from here)

The code here is updated and working up to Minecraft 1.8.9.
I will try to do the 1.9 stuff in the next weeks...

**Comment by mrkite** [comment]
New version fixed.
