### ISSUE TITLE
Program instructions/documentation/version number & other comments

### ISSUE THREAD

**Issue by BigAlanM** [mrkite/minutor#84]
It would be nice if there were some sort of help or a file download with documentation of how to use the functions of the program.
Also, I found out by accident that the Windows file keeps being updated with new features and block definitions without changing the version number or letting people know that that there is a newer version.
Due to that I keep having to download the .zip and check to see if the program has been changed.

What's the purpose/use of "Cave Mode" and why is it not working?

**Comment by erich666** [comment]
Mineways was built atop minutor and has a bit of documentation about cave mode, etc. See http://www.realtimerendering.com/erich/minecraft/public/mineways/reference.html

Here's what cave mode looks like in Mineways: http://postimg.org/image/za9e8xiqd/

**Comment by EtlamGit** [comment]
**Cave mode** showed underground caves in the old 1.6.3 build of Minutor.
With the complete rewrite of the code base with version 2 it was missed to be implemented, together with some other features. The entry in the menu is still there as a reminder for me to start development on this topic. Obviously I forgot to do that...

Some sort of **documentation** is also planned. But more as a reference for used colors. Maybe we have to do some text also? Especially for the command line syntax it should be outside the program itself.

Could you please describe in more detail, what you mean with the **updated with new features** problem? There should be the version number of each definition file under: _View->Manage definitions_

**Comment by BigAlanM** [comment]
The download site doesn't mention what version is current.

**Comment by EtlamGit** [comment]
I still do not get your point, sorry. But I also self compile and do not use the official downloads...

There was a quite long time without updates of Minutor. During that time it was possible to update the definition files by hand. Do you mean that with "download .zip" ? There was also an automatic definition file update from the official download site.
Starting with Minutor 2.1 there is an automatic update of the definition files directly from the GitHub repository here. The definition files have a strict version information based on the Minecraft version they belong to. So Minutor should always have the latest definition files at the moment they are published here. At the moment I'm working on the 1.10 update.
For the program and its features itself: during development you have to self compile or to wait until the next release.

**Comment by mrkite** [comment]
If I move the executables over to github, then the version labelling won't be a problem.

**Comment by EtlamGit** [comment]
Regarding documentation, I see two possible solutions how to do it:

- Write a couple of text.md files, similar to README.md also linking to each other. They could be placed in a separate documentation folder.
- Add a gh-pages branch to Minutor and place all documentation there. This would generate a website look when browsing to this repository.

Do you have any preference?

**Comment by mrkite** [comment]
I created an empty home page on the wiki.  See if you can modify it.  I don't see anywhere to grant or restrict permissions for the wiki, so I'm assuming it's open to anyone now that I've created a stub.
