### ISSUE TITLE
unhandled exception during debugging

### ISSUE THREAD

**Issue by EtlamGit** [mrkite/minutor#90]
During debugging I always get an unhandled Exception:0x13fe59b15, code: 0xc0000005: read access violation at: 0x0, flags=0x0 (first chance)
In Release mode everything runs fine. As I have tried to find the error for about a year now (but failed so far), I place it as an issue here. Probably it is somewhere in the automatic definition update process.

Normal debugging is possible, again when changing in minutor.cpp:

```
#ifdef DEBUG
  if (settings->autoUpdate)
    dm->autoUpdate();
#endif

```

**Comment by mrkite** [comment]
I've had similar problems with debug mode.  I thought it was related to my debug kits being screwed up in Qt Creator.

**Comment by madmaxoft** [comment]
I don't see this behavior in my debugger, everything works normally without any changes to the code.

I'm using self-compiled static 32-bit Qt 5.6 on 64-bit Windows 8.

**Comment by EtlamGit** [comment]
Here it is: self-compiled static 64bit Qt 5.6.0 on Windows 7 64bit
But for older Qt versions it was the same.
