### ISSUE TITLE
Save PNG doesn't append the .PNG

### ISSUE THREAD

**Issue by BigAlanM** [mrkite/minutor#91]
This was just mentioned in the MC Forums Minutor thread,
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1260549-minutor-osx-linux-windows-2-0-1?page=40  post #802 on 8/20/2016.

I've verified it with my system.
System:  PC running Windows 10, Java 1.8.0_101 with the latest download of Minutor.

**Comment by madmaxoft** [comment]
This has already been reported and fixed (#83)

**Comment by BigAlanM** [comment]
OOPS!  My error and bad memory.
