### ISSUE TITLE
Cannot open saved worlds from the File - Open World menu on Mac

### ISSUE THREAD

**Issue by rowdy-fms** [mrkite/minutor#93]
OS X 10.11.6, Minutor v2.1.0, Minecraft 1.10.2

Worlds are saved in the default location: /Users/<username>/Library/Application Support/minecraft/saves

There are several saved worlds therein.

Starting Minutor and selecting File - Open World from the menu does not show any worlds to open.

It is still possible to select File - Open and manually browse to the world's save directory to open a world, but as the Library folder is hidden this is an extra complication.

**Comment by EtlamGit** [comment]
Sorry nobody responded to you for that long time (I skipped reading after the word Mac).
But:
Did you try to use Help -> Settings
and enter a different "Minecraft Location"

**Comment by rowdy-fms** [comment]
Thank you for the response :)

I am using the default location for saves, but changed the Minutor preference anyway, and restarted it just in case.

<img width="512" alt="screen shot 2017-10-09 at 7 49 46 am" src="https://user-images.githubusercontent.com/5975003/31321058-e469b96a-acca-11e7-9ad7-31e02ee6a025.png">

It did not help - I still cannot see any worlds listed under File - Open World.

<img width="449" alt="screen shot 2017-10-09 at 8 20 13 am" src="https://user-images.githubusercontent.com/5975003/31321065-f3e9ba66-acca-11e7-9915-9e7aabeed7c0.png">

Still using the same version of OS X and Minutor but Minecraft is now version 1.12.2.

**Comment by EtlamGit** [comment]
As I do not have a Mac, I'm not able to support further, sorry.
Maybe someone else with a Mac pops in in the near future ;-)

**Comment by madmaxoft** [comment]
I have the same issue on Windows.

I'll try to debug this, I think I can compile Minutor on this computer :)

**Comment by madmaxoft** [comment]
@rowdy-fms If you re-check the "Use default location" in the settings, does it work? It started working for me from that moment on - a fresh install of Minutor doesn't properly initialize the internal value of default location. There's even no restart needed, it works as soon as I close the settings window.

**Comment by madmaxoft** [comment]
Note that you should not point to the `saves` folder, but rather one folder above it.

**Comment by madmaxoft** [comment]
Any chance you could compile #121 and try it out? I can only test on Windows, and the change seems to work for me.

**Comment by rowdy-fms** [comment]
Changing the Minecraft Location to the directory above `saves` worked.

Changing the setting back to use the default location (after that) also worked.

Not sure I can setup my work Mac to compile it, but I can probably try at home soon.

Thank you for the responses!

**Comment by madmaxoft** [comment]
The PR was already merged, so it should work for you in the next release. Good to hear that the workaround fixed it for you, too.
